// Textos das estatísticas, das conquistas (descrições) e da tela de recordes ampliada.
// Os nomes das conquistas ficam em src/game/desktop.ts (ACHIEVEMENTS), junto com os ids da Steam.
import { registerStrings } from '../i18n';

registerStrings('stats', {
  pt: {
    'tab.tracks': 'Pistas',
    'tab.players': 'Jogadores',
    'tab.achievements': 'Conquistas',
    'tabs.hint': '◀ ▶ trocam de aba',
    'tracks.hint': 'Melhor volta e melhor tempo de corrida por número de voltas, com quem fez.',
    'players.all': 'Todos os jogadores',
    'players.allNote': 'Soma de todos os nomes, inclusive os que já saíram da lista (ficam os {max} mais recentes). Numa corrida com 4 jogadores, cada um conta a sua.',
    'players.summary': '{races} corridas · {wins} vitórias',
    'players.empty': 'Nenhuma corrida registrada ainda — as estatísticas aparecem ao fim da primeira.',
    'players.hint': 'Estatísticas pelo nome usado no lobby.',
    'stat.races': 'Corridas',
    'stat.wins': 'Vitórias',
    'stat.podiums': 'Pódios',
    'stat.coopWins': 'Vitórias em co‑op', // hífen que não quebra: "co-" / "op" em duas linhas no cartão
    'stat.laps': 'Voltas',
    'stat.meters': 'Distância',
    'stat.raceTicks': 'Tempo de corrida',
    'stat.nitros': 'Nitros',
    'stat.towsGiven': 'Empurrões dados',
    'stat.towsReceived': 'Empurrões recebidos',
    'stat.collisions': 'Colisões',
    'stat.crashes': 'Batidas no cenário',
    'stat.pitStops': 'Paradas no box',
    'best.title': 'Melhor posição por pista',
    'best.count': '{n} de {total} pistas',
    'best.none': 'Nenhuma corrida registrada fora do contra-relógio.',
    'best.pos': '{n}º',
    'ach.progress': '{n} de {total} desbloqueadas',
    'ach.unlocked': 'Desbloqueadas',
    'ach.locked': 'Bloqueadas',
    'ach.stateOn': 'Desbloqueada',
    'ach.stateOff': 'Bloqueada',
    'results.title': 'Conquistas desbloqueadas',
    hudMany: 'CONQUISTAS: {names}',
    'achDesc.PRIMEIRA_VITORIA': 'Vencer uma corrida (o contra-relógio não conta).',
    'achDesc.COPA_BRASIL': 'Concluir a Copa Brasil.',
    'achDesc.COPA_EUA': 'Concluir a Copa Estados Unidos.',
    'achDesc.COPA_JAPAO': 'Concluir a Copa Japão.',
    'achDesc.COPA_EUROPA': 'Concluir a Copa Europa.',
    'achDesc.EQUIPE_COMPLETA': 'Correr uma corrida com 4 jogadores.',
    'achDesc.SEM_BOX': 'Vencer uma corrida sem parar no box.',
    'achDesc.NITRO_TRIPLO': 'Usar 3 nitros numa mesma volta.',
    'achDesc.EMPURRAO': 'Dar um empurrão num companheiro parado.',
    'achDesc.VOLTA_PERFEITA': 'Completar uma volta sem sair do asfalto.',
    'achDesc.CAMPEAO': 'Concluir uma copa na dificuldade Campeão.',
    'achDesc.MADRUGADA': 'Vencer numa pista noturna.',
    'achDesc.PODIO_DE_EQUIPE': 'Três jogadores no pódio (1º, 2º e 3º) numa corrida contra a IA.',
    'achDesc.DO_ULTIMO_AO_PRIMEIRO': 'Vencer uma corrida em que você estava em último ao fechar a primeira volta.',
    'achDesc.SEM_ARRANHAO': 'Terminar uma corrida contra a IA sem bater em carro nem no cenário.',
    'achDesc.MARATONA': 'Somar 1.000 km de corrida, juntando todos os jogadores.',
    'achDesc.MESTRE_DO_VACUO': 'Passar 60 segundos no vácuo de outros carros numa mesma corrida.',
    'achDesc.NITRO_NA_BANDEIRA': 'Cruzar a linha de chegada com o nitro ligado.',
    'achDesc.DEZ_VITORIAS': 'Somar 10 vitórias (o contra-relógio não conta).',
    'achDesc.GIRO_COMPLETO': 'Correr em todas as pistas do jogo (o contra-relógio não conta).',
  },
  en: {
    'tab.tracks': 'Tracks',
    'tab.players': 'Players',
    'tab.achievements': 'Achievements',
    'tabs.hint': '◀ ▶ switch tabs',
    'tracks.hint': 'Best lap and best race time per lap count, with who set them.',
    'players.all': 'All players',
    'players.allNote': 'Sum of every name, including the ones that left the list (the {max} most recent are kept). In a 4-player race, each player counts their own.',
    'players.summary': '{races} races · {wins} wins',
    'players.empty': 'No races recorded yet — stats show up after the first one.',
    'players.hint': 'Stats by the name used in the lobby.',
    'stat.races': 'Races',
    'stat.wins': 'Wins',
    'stat.podiums': 'Podiums',
    'stat.coopWins': 'Co‑op wins',
    'stat.laps': 'Laps',
    'stat.meters': 'Distance',
    'stat.raceTicks': 'Race time',
    'stat.nitros': 'Nitros',
    'stat.towsGiven': 'Pushes given',
    'stat.towsReceived': 'Pushes received',
    'stat.collisions': 'Collisions',
    'stat.crashes': 'Roadside crashes',
    'stat.pitStops': 'Pit stops',
    'best.title': 'Best position per track',
    'best.count': '{n} of {total} tracks',
    'best.none': 'No races recorded outside time trial.',
    'best.pos': 'P{n}',
    'ach.progress': '{n} of {total} unlocked',
    'ach.unlocked': 'Unlocked',
    'ach.locked': 'Locked',
    'ach.stateOn': 'Unlocked',
    'ach.stateOff': 'Locked',
    'results.title': 'Achievements unlocked',
    hudMany: 'ACHIEVEMENTS: {names}',
    'achDesc.PRIMEIRA_VITORIA': 'Win a race (time trial does not count).',
    'achDesc.COPA_BRASIL': 'Complete the Brazil Cup.',
    'achDesc.COPA_EUA': 'Complete the USA Cup.',
    'achDesc.COPA_JAPAO': 'Complete the Japan Cup.',
    'achDesc.COPA_EUROPA': 'Complete the Europe Cup.',
    'achDesc.EQUIPE_COMPLETA': 'Race with 4 players.',
    'achDesc.SEM_BOX': 'Win a race without a pit stop.',
    'achDesc.NITRO_TRIPLO': 'Use 3 nitros in a single lap.',
    'achDesc.EMPURRAO': 'Push a stalled teammate.',
    'achDesc.VOLTA_PERFEITA': 'Complete a lap without leaving the tarmac.',
    'achDesc.CAMPEAO': 'Complete a cup on Champion difficulty.',
    'achDesc.MADRUGADA': 'Win on a night track.',
    'achDesc.PODIO_DE_EQUIPE': 'Three players take the podium (1st, 2nd and 3rd) in a race against the AI.',
    'achDesc.DO_ULTIMO_AO_PRIMEIRO': 'Win a race in which you were last at the end of the first lap.',
    'achDesc.SEM_ARRANHAO': 'Finish a race against the AI without hitting a car or anything on the roadside.',
    'achDesc.MARATONA': 'Drive 1,000 km in total, all players combined.',
    'achDesc.MESTRE_DO_VACUO': 'Spend 60 seconds in other cars\' slipstream in a single race.',
    'achDesc.NITRO_NA_BANDEIRA': 'Cross the finish line with nitro active.',
    'achDesc.DEZ_VITORIAS': 'Win 10 races (time trial does not count).',
    'achDesc.GIRO_COMPLETO': 'Race on every track in the game (time trial does not count).',
  },
});
