// Textos do Modo Carreira e do "Continuar" do campeonato, em PT e EN. Estende também 'ui' (itens do
// menu principal e botão da classificação) e 'core' (apresentação dos carros novos): registerStrings
// mescla no namespace, sem editar os strings.ts das outras pastas.
import { registerStrings } from '../i18n';

registerStrings('ui', {
  pt: {
    'main.career': 'Carreira',
    'main.continue': 'Continuar',
    'main.hint.career': 'Prêmios em dinheiro, oito carros e melhorias de copa em copa',
    'main.hint.continue': '{cup} — corrida {n} de {m}',
    'standings.garage': 'GARAGEM',
  },
  en: {
    'main.career': 'Career',
    'main.continue': 'Continue',
    'main.hint.career': 'Prize money, eight cars and upgrades, cup after cup',
    'main.hint.continue': '{cup} — race {n} of {m}',
    'standings.garage': 'GARAGE',
  },
});

registerStrings('core', {
  pt: {
    'car.sucuri.blurb': 'Um tanque para a corrida inteira e boa velocidade. Pesado para arrancar.',
    'car.carcara.blurb': 'Dispara na saída e cola na curva. Perde para todos no fim da reta longa.',
    'car.pororoca.blurb': 'Ninguém anda mais na reta. Arisco nas curvas e bebe como nenhum outro.',
    'car.boitata.blurb': 'Forte em tudo, sem ponto fraco. O preço é o mais alto da garagem.',
  },
  en: {
    'car.sucuri.blurb': 'One tank lasts the whole race, and it is quick. Heavy off the line.',
    'car.carcara.blurb': 'Launches hard and sticks to corners. Loses to everyone at the end of a long straight.',
    'car.pororoca.blurb': 'Nothing is faster on a straight. Twitchy in corners and drinks like no other.',
    'car.boitata.blurb': 'Strong at everything, no weak spot. The priciest car in the garage.',
  },
});

registerStrings('career', {
  pt: {
    'money': '$ {v}',
    'mode.coop': 'Cooperativo',
    'mode.versus': 'Versus',
    'mode.solo': 'Solo',

    'hub.title': 'Carreira',
    'hub.intro': 'Corra as copas em ordem. Cada corrida paga um prêmio pela posição; entre as corridas, a garagem vende carros e melhorias. Os rivais também evoluem de copa em copa.',
    'hub.introCoop': 'No cooperativo a equipe divide um cofre e ganha bônus pela colocação da equipe; no versus, cada um tem a sua carteira.',
    'hub.none': 'Nenhuma carreira salva.',
    'hub.continue': 'Continuar carreira',
    'hub.new': 'Nova carreira',
    'hub.confirmNew': 'Apagar a salva e começar outra?',
    'hub.cup': 'Copa atual',
    'hub.race': 'corrida {n} de {m}',
    'hub.attempt': 'tentativa {n}',
    'hub.drivers': 'Pilotos',
    'hub.mode': 'Modo',
    'hub.money': 'Dinheiro',
    'hub.cars': 'Carros comprados',
    'hub.races': 'Corridas',
    'hub.completed': 'CARREIRA CONCLUÍDA',
    'hub.progress': 'Copa {i} de {n}',

    'lobby.carNote': 'Carro e melhorias: na garagem',
    'lobby.resume': 'Continuar',
    'lobby.resumeHint': 'Os mesmos {n} pilotos da partida salva entram, a partir do P1',
    'lobby.fixedMode': 'Modo: {mode}',

    'garage.title': 'Garagem',
    'garage.progress': 'Copa {i} de {n}',
    'garage.next': 'Próxima: {track} — corrida {n} de {m}',
    'garage.wallet': 'Carteira',
    'garage.teamWallet': 'Cofre da equipe',
    'garage.selected': 'NA PISTA',
    'garage.owned': 'NA GARAGEM',
    'garage.forSale': 'À VENDA',
    'garage.buyHint': 'Enter compra',
    'garage.need': 'faltam {price}',
    'garage.upgrades': 'Melhorias',
    'garage.max': 'MÁX',
    'garage.stats': 'Atributos',
    'garage.part.engine': 'Motor',
    'garage.part.turbo': 'Turbo',
    'garage.part.tires': 'Pneus',
    'garage.part.brakes': 'Freios',
    'garage.part.tank': 'Tanque',
    'garage.part.nitro': 'Nitro',
    'garage.effect.engine': 'velocidade máxima',
    'garage.effect.turbo': 'aceleração',
    'garage.effect.tires': 'curvas',
    'garage.effect.brakes': 'frenagem',
    'garage.effect.tank': 'consumo menor',
    'garage.effect.nitro': '+1 carga',
    'garage.capped': 'no teto deste carro',
    'garage.stat.topSpeed': 'Velocidade',
    'garage.stat.accel': 'Aceleração',
    'garage.stat.handling': 'Curvas',
    'garage.stat.brake': 'Freios',
    'garage.stat.economy': 'Economia',
    'garage.stat.nitro': 'Nitro',
    'garage.ready': 'PRONTO',
    'garage.race': 'CORRER',
    'garage.menu': 'MENU',
    'garage.waiting': 'Esperando os outros pilotos',
    'garage.hint': '↑↓ escolhe · ←→ troca de carro · Enter compra · Esc volta ao menu (a carreira fica salva)',
    'garage.msg.bought': 'Comprado!',
    'garage.msg.noMoney': 'Dinheiro insuficiente',
    'garage.msg.maxLevel': 'Já está no máximo',
    'garage.msg.notOwned': 'Compre o carro primeiro',
    'garage.msg.locked': 'Tire o PRONTO para mexer',
    'garage.report.title': 'Última corrida — {track}',
    'garage.report.row': '{name}: {pos}º  +{prize}',
    'garage.report.team': 'Bônus da equipe ({rank}ª): +{prize}',
    'garage.report.eliminated': 'ELIMINADO — só a ajuda de custo (metade do prêmio); a {cup} recomeça da primeira pista (tentativa {n})',
    'garage.report.cupDone': '{cup} CONCLUÍDA! Agora: {next}.',
    'garage.report.careerDone': 'CARREIRA CONCLUÍDA! Todas as copas vencidas.',
    'garage.welcome': 'Bem-vindos! Gastem o dinheiro inicial numa melhoria antes da primeira corrida.',
    'garage.welcomeSolo': 'Bem-vindo! Gaste o dinheiro inicial numa melhoria antes da primeira corrida.',
  },
  en: {
    'money': '${v}',
    'mode.coop': 'Co-op',
    'mode.versus': 'Versus',
    'mode.solo': 'Solo',

    'hub.title': 'Career',
    'hub.intro': 'Race the cups in order. Every race pays prize money by position; between races the garage sells cars and upgrades. Rivals get stronger cup after cup.',
    'hub.introCoop': 'In co-op the team shares one vault and earns a bonus for the team placing; in versus everyone keeps their own wallet.',
    'hub.none': 'No saved career.',
    'hub.continue': 'Continue career',
    'hub.new': 'New career',
    'hub.confirmNew': 'Erase the saved one and start over?',
    'hub.cup': 'Current cup',
    'hub.race': 'race {n} of {m}',
    'hub.attempt': 'attempt {n}',
    'hub.drivers': 'Drivers',
    'hub.mode': 'Mode',
    'hub.money': 'Money',
    'hub.cars': 'Cars bought',
    'hub.races': 'Races',
    'hub.completed': 'CAREER COMPLETE',
    'hub.progress': 'Cup {i} of {n}',

    'lobby.carNote': 'Car and upgrades: in the garage',
    'lobby.resume': 'Continue',
    'lobby.resumeHint': 'The same {n} drivers from the saved game join, starting from P1',
    'lobby.fixedMode': 'Mode: {mode}',

    'garage.title': 'Garage',
    'garage.progress': 'Cup {i} of {n}',
    'garage.next': 'Next: {track} — race {n} of {m}',
    'garage.wallet': 'Wallet',
    'garage.teamWallet': 'Team vault',
    'garage.selected': 'RACING',
    'garage.owned': 'IN GARAGE',
    'garage.forSale': 'FOR SALE',
    'garage.buyHint': 'Enter buys',
    'garage.need': '{price} short',
    'garage.upgrades': 'Upgrades',
    'garage.max': 'MAX',
    'garage.stats': 'Stats',
    'garage.part.engine': 'Engine',
    'garage.part.turbo': 'Turbo',
    'garage.part.tires': 'Tyres',
    'garage.part.brakes': 'Brakes',
    'garage.part.tank': 'Tank',
    'garage.part.nitro': 'Nitro',
    'garage.effect.engine': 'top speed',
    'garage.effect.turbo': 'acceleration',
    'garage.effect.tires': 'cornering',
    'garage.effect.brakes': 'braking',
    'garage.effect.tank': 'lower consumption',
    'garage.effect.nitro': '+1 charge',
    'garage.capped': 'maxed on this car',
    'garage.stat.topSpeed': 'Top speed',
    'garage.stat.accel': 'Acceleration',
    'garage.stat.handling': 'Handling',
    'garage.stat.brake': 'Brakes',
    'garage.stat.economy': 'Economy',
    'garage.stat.nitro': 'Nitro',
    'garage.ready': 'READY',
    'garage.race': 'RACE',
    'garage.menu': 'MENU',
    'garage.waiting': 'Waiting for the other drivers',
    'garage.hint': '↑↓ select · ←→ change car · Enter buys · Esc back to menu (the career is saved)',
    'garage.msg.bought': 'Bought!',
    'garage.msg.noMoney': 'Not enough money',
    'garage.msg.maxLevel': 'Already maxed out',
    'garage.msg.notOwned': 'Buy the car first',
    'garage.msg.locked': 'Undo READY to make changes',
    'garage.report.title': 'Last race — {track}',
    'garage.report.row': '{name}: P{pos}  +{prize}',
    'garage.report.team': 'Team bonus (#{rank}): +{prize}',
    'garage.report.eliminated': 'ELIMINATED — half prize only; the {cup} restarts from its first track (attempt {n})',
    'garage.report.cupDone': '{cup} COMPLETE! Next up: {next}.',
    'garage.report.careerDone': 'CAREER COMPLETE! Every cup won.',
    'garage.welcome': 'Welcome! Spend the starting money on an upgrade before the first race.',
    'garage.welcomeSolo': 'Welcome! Spend the starting money on an upgrade before the first race.',
  },
});
