// Textos do tutorial de 90 segundos (menu, painel da corrida guiada e tela final), em PT e EN
// (tests/i18n.test.ts exige os dois).
import { registerStrings } from '../i18n';

registerStrings('tutorial', {
  pt: {
    'menu': 'Como jogar',
    'menu.hint': 'Tutorial de 90 segundos: acelerar, curvas, freio, nitro, box e empurrão',
    'offer.badge': 'NOVO',
    'offer.title': 'Primeira vez?',
    'offer.text': 'Aprenda a correr em 90 segundos: escolha Como jogar.',

    'join.title': 'Como jogar',
    'join.sub': 'Tutorial de 90 segundos · uma volta guiada, sem adversários',
    'join.hint': 'Enter ou Espaço: teclado 1 · F: teclado 2 · A: controle',
    'join.coop': 'Com 2 ou mais jogadores, a última lição é empurrar o companheiro parado.',
    'join.empty': 'Aperte para entrar',
    'join.need': 'Quem vai jogar aperta o botão de entrar',
    'join.start': 'COMEÇAR',
    'join.leave': 'Esc / B sai do assento',

    'counter': 'PASSO {n}/{total}',
    'skip': '{key}: pular tutorial',
    'key.steer': 'Virar',
    'key.stick': 'Analógico',

    'step.throttle.title': 'Acelere',
    'step.throttle.text': 'Segure o acelerador até {kmh} km/h.',
    'step.curve.title': 'Curva média',
    'step.curve.text': 'Vire junto com a curva e fique no asfalto até o fim dela.',
    'step.brake.title': 'Curva forte',
    'step.brake.text': 'Freie ANTES da curva forte (placas) e contorne sem ir para a grama.',
    'step.nitro.title': 'Nitro',
    'step.nitro.text': 'Reta livre: solte o nitro.',
    'step.pit.title': 'Box',
    'step.pit.text': 'Tanque baixo! Freie, entre no box à direita e fique na faixa até abastecer.',
    'step.tow.title': 'Empurrão',
    'step.tow.text': '{name} parou! Venha de trás acelerando e passe colado nele para empurrar.',
    'step.tow.before': 'Na reta, o carro de {name} vai parar: fique atrás dele até ele parar.',
    'step.stalled.title': 'Empurrão',
    'step.stalled.text': 'Siga até a reta: lá o seu carro vai parar de propósito.',
    'step.stalled.parked': 'Seu carro parou! Espere um companheiro passar colado e te empurrar.',
    'step.wait.title': 'Muito bem!',
    'step.wait.text': 'Continue na pista enquanto a equipe termina o box.',
    'step.done.title': 'Tutorial concluído!',
    'step.done.text': 'Você aprendeu o essencial.',

    'ok': 'Muito bem!',
    'retry.offroad': 'Saiu do asfalto: tente de novo na próxima volta',
    'retry.fast': 'Rápido demais! Freie antes da curva: de novo na próxima volta',
    'retry.pitMissed': 'Passou do box: entre na próxima volta',
    'retry.pitShort': 'Saiu antes de abastecer: freie antes do box na próxima volta',
    'noNitro': 'Sem nitro: siga para o box',
    'parkedYou': 'Pane! Espere o empurrão',
    'parkedMate': '{name} parou: vá empurrar!',
    'towGiven': 'Empurrão dado!',
    'towMissed': 'Passou direto: dê a volta e passe colado, acelerando',
    'finished': 'TUTORIAL CONCLUÍDO!',

    'done.title': 'Parabéns!',
    'done.sub': 'Você está pronto para correr. As regras de ouro:',
    'done.skippedTitle': 'Regras de ouro',
    'done.skippedSub': 'O essencial para a primeira corrida:',
    'rule.brake': 'Curva forte pede freio ANTES dela, não no meio.',
    'rule.grass': 'A grama derruba a velocidade: fique no asfalto.',
    'rule.nitro': 'Nitro rende mais na reta. São 3 por corrida; no co-op, um cofre da equipe.',
    'rule.pit': 'Tanque piscando? Box à direita na reta de largada.',
    'rule.tow': 'Companheiro parado? Passe colado e dê um empurrão.',
    'done.cup': 'Correr a {cup}',
    'done.main': 'Menu principal',
  },
  en: {
    'menu': 'How to play',
    'menu.hint': '90-second tutorial: throttle, corners, braking, nitro, pit stop and push',
    'offer.badge': 'NEW',
    'offer.title': 'First time?',
    'offer.text': 'Learn to race in 90 seconds: pick How to play.',

    'join.title': 'How to play',
    'join.sub': '90-second tutorial · one guided lap, no opponents',
    'join.hint': 'Enter or Space: keyboard 1 · F: keyboard 2 · A: gamepad',
    'join.coop': 'With 2 or more players, the last lesson is pushing your stalled teammate.',
    'join.empty': 'Press to join',
    'join.need': 'Whoever plays presses the join button',
    'join.start': 'START',
    'join.leave': 'Esc / B leaves the seat',

    'counter': 'STEP {n}/{total}',
    'skip': '{key}: skip tutorial',
    'key.steer': 'Steer',
    'key.stick': 'Stick',

    'step.throttle.title': 'Accelerate',
    'step.throttle.text': 'Hold the throttle until {kmh} km/h.',
    'step.curve.title': 'Medium corner',
    'step.curve.text': 'Steer with the corner and stay on the tarmac to the end of it.',
    'step.brake.title': 'Sharp corner',
    'step.brake.text': 'Brake BEFORE the sharp corner (signs) and take it without hitting the grass.',
    'step.nitro.title': 'Nitro',
    'step.nitro.text': 'Clear straight: fire the nitro.',
    'step.pit.title': 'Pit stop',
    'step.pit.text': 'Low fuel! Brake, take the pit lane on the right and stay in it until refuelled.',
    'step.tow.title': 'Push',
    'step.tow.text': '{name} has stalled! Come from behind at speed and pass right by them to push.',
    'step.tow.before': 'On the straight, {name}\'s car will stall: stay behind until it stops.',
    'step.stalled.title': 'Push',
    'step.stalled.text': 'Head for the straight: your car will stall there on purpose.',
    'step.stalled.parked': 'Your car stalled! Wait for a teammate to drive right behind you and push.',
    'step.wait.title': 'Well done!',
    'step.wait.text': 'Keep driving while the team finishes the pit stop.',
    'step.done.title': 'Tutorial complete!',
    'step.done.text': 'You have learned the essentials.',

    'ok': 'Well done!',
    'retry.offroad': 'Off the tarmac: try again next lap',
    'retry.fast': 'Too fast! Brake before the corner: again next lap',
    'retry.pitMissed': 'Missed the pit: take it next lap',
    'retry.pitShort': 'Left before refuelling: brake before the pit next lap',
    'noNitro': 'No nitro left: head for the pit',
    'parkedYou': 'Breakdown! Wait for the push',
    'parkedMate': '{name} stalled: go push!',
    'towGiven': 'Push given!',
    'towMissed': 'Went past: come round again and pass right behind, at speed',
    'finished': 'TUTORIAL COMPLETE!',

    'done.title': 'Congratulations!',
    'done.sub': 'You are ready to race. The golden rules:',
    'done.skippedTitle': 'Golden rules',
    'done.skippedSub': 'The essentials for your first race:',
    'rule.brake': 'A sharp corner needs braking BEFORE it, not in the middle.',
    'rule.grass': 'Grass kills your speed: stay on the tarmac.',
    'rule.nitro': 'Nitro pays off on straights. 3 per race; in co-op, a team pool.',
    'rule.pit': 'Fuel gauge blinking? Pit lane on the right of the start straight.',
    'rule.tow': 'Teammate stalled? Drive right behind them and give a push.',
    'done.cup': 'Race the {cup}',
    'done.main': 'Main menu',
  },
});
