// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Padelizou.Models;

#nullable disable

namespace Padelizou.Migrations
{
    [DbContext(typeof(DbPadelContext))]
    [Migration("20260720223500_AddAgendaPreferenciasJogador")]
    partial class AddAgendaPreferenciasJogador
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Padelizou.Models.AvisoJogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaPadraoId")
                        .HasColumnType("int");

                    b.Property<int>("ClubeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CriadorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPadraoId");

                    b.HasIndex("ClubeId");

                    b.HasIndex("CriadorId");

                    b.ToTable("AvisoJogo");
                });

            modelBuilder.Entity("Padelizou.Models.AvisoParceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("CriadorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeTorneio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CriadorId");

                    b.ToTable("AvisoParceiro");
                });

            modelBuilder.Entity("Padelizou.Models.CandidaturaParceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvisoParceiroId")
                        .HasColumnType("int");

                    b.Property<int>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AvisoParceiroId");

                    b.HasIndex("CandidatoId");

                    b.ToTable("CandidaturaParceiro");
                });

            modelBuilder.Entity("Padelizou.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("TorneioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC079FE58FF8");

                    b.HasIndex("TorneioId");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Padelizou.Models.Clube", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clubes");
                });

            modelBuilder.Entity("Padelizou.Models.Dupla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Grupo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GrupoTorneioId")
                        .HasColumnType("int");

                    b.Property<bool>("ImpedimentoSabadoManha")
                        .HasColumnType("bit");

                    b.Property<bool>("ImpedimentoSabadoTarde")
                        .HasColumnType("bit");

                    b.Property<bool>("ImpedimentoSextaNoite")
                        .HasColumnType("bit");

                    b.Property<int>("Jogador1Id")
                        .HasColumnType("int");

                    b.Property<int>("Jogador2Id")
                        .HasColumnType("int");

                    b.Property<int?>("TorneioId")
                        .HasColumnType("int");

                    b.Property<string>("UltimaFase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Dupla__3214EC07E192F96C");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("GrupoTorneioId");

                    b.HasIndex("Jogador1Id");

                    b.HasIndex("Jogador2Id");

                    b.HasIndex("TorneioId");

                    b.ToTable("Dupla", (string)null);
                });

            modelBuilder.Entity("Padelizou.Models.HorarioDisponivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<int>("LocalAulaId")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocalAulaId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("HorarioDisponivel");
                });

            modelBuilder.Entity("Padelizou.Models.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AgendaMostrarAlunos")
                        .HasColumnType("bit");

                    b.Property<bool>("AgendaMostrarAulas")
                        .HasColumnType("bit");

                    b.Property<bool>("AgendaMostrarJogosSemanais")
                        .HasColumnType("bit");

                    b.Property<bool>("AgendaMostrarTorneios")
                        .HasColumnType("bit");

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("CPF");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsProfessor")
                        .HasColumnType("bit");

                    b.Property<string>("LadoQuadra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("NotificarEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("NotificarWhatsApp")
                        .HasColumnType("bit");

                    b.Property<int>("PontuacaoGlobal")
                        .HasColumnType("int");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TimeId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Jogador__3214EC07E9B77CE2");

                    b.HasIndex("TimeId");

                    b.HasIndex(new[] { "Cpf" }, "UQ__Jogador__C1F897318C6002EF")
                        .IsUnique();

                    b.ToTable("Jogador", (string)null);
                });

            modelBuilder.Entity("Padelizou.Models.JogadorCategoria", b =>
                {
                    b.Property<int>("JogadorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaPadraoId")
                        .HasColumnType("int");

                    b.HasKey("JogadorId", "CategoriaPadraoId");

                    b.HasIndex("CategoriaPadraoId");

                    b.ToTable("JogadorCategoria");
                });

            modelBuilder.Entity("Padelizou.Models.JogadorClube", b =>
                {
                    b.Property<int>("JogadorId")
                        .HasColumnType("int");

                    b.Property<int>("ClubeId")
                        .HasColumnType("int");

                    b.HasKey("JogadorId", "ClubeId");

                    b.HasIndex("ClubeId");

                    b.ToTable("JogadorClube");
                });

            modelBuilder.Entity("Padelizou.Models.JogadorDiaHorario", b =>
                {
                    b.Property<int>("JogadorId")
                        .HasColumnType("int");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<string>("Periodo")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("JogadorId", "DiaSemana", "Periodo");

                    b.ToTable("JogadorDiaHorario");
                });

            modelBuilder.Entity("Padelizou.Models.JogoSemanal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataJogo")
                        .HasColumnType("datetime2");

                    b.Property<int>("Dupla1Jogador1Id")
                        .HasColumnType("int");

                    b.Property<int>("Dupla1Jogador2Id")
                        .HasColumnType("int");

                    b.Property<int>("Dupla2Jogador1Id")
                        .HasColumnType("int");

                    b.Property<int>("Dupla2Jogador2Id")
                        .HasColumnType("int");

                    b.Property<int>("GamesDupla1")
                        .HasColumnType("int");

                    b.Property<int>("GamesDupla2")
                        .HasColumnType("int");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<int>("RegistradoPorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Dupla1Jogador1Id");

                    b.HasIndex("Dupla1Jogador2Id");

                    b.HasIndex("Dupla2Jogador1Id");

                    b.HasIndex("Dupla2Jogador2Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("RegistradoPorId");

                    b.ToTable("JogoSemanal");
                });

            modelBuilder.Entity("Padelizou.Models.LocalAula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<decimal?>("CustoPorAula")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecoPadrao")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("LocalAula");
                });

            modelBuilder.Entity("Padelizou.Models.Organizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Organiza__3214EC079F755F08");

                    b.HasIndex(new[] { "Codigo" }, "UQ__Organiza__06370DAC46EF791B")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Organiza__A9D10534817DC0DF")
                        .IsUnique();

                    b.ToTable("Organizador", (string)null);
                });

            modelBuilder.Entity("Padelizou.Models.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Dupla1Id")
                        .HasColumnType("int");

                    b.Property<int>("Dupla2Id")
                        .HasColumnType("int");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GamesDupla1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("GamesDupla2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("HorarioFimReal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HorarioInicioReal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HorarioPrevisto")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkTransmissao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeQuadra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SendoTransmitida")
                        .HasColumnType("bit");

                    b.Property<int?>("SetsDupla1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("SetsDupla2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TorneioId")
                        .HasColumnType("int");

                    b.Property<int?>("VencedorId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Partida__3214EC0755DC2078");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Dupla1Id");

                    b.HasIndex("Dupla2Id");

                    b.ToTable("Partida");
                });

            modelBuilder.Entity("Padelizou.Models.Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubeId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClubeId");

                    b.ToTable("Times");
                });

            modelBuilder.Entity("Padelizou.Models.Torneio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassificadosPorGrupo")
                        .HasColumnType("int");

                    b.Property<int>("ClubeId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FormatoUnico")
                        .HasColumnType("bit");

                    b.Property<int>("GamesFaseFinal")
                        .HasColumnType("int");

                    b.Property<int>("GamesFaseGrupos")
                        .HasColumnType("int");

                    b.Property<int>("GamesFaseMataMata")
                        .HasColumnType("int");

                    b.Property<string>("LocalTorneio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("OrganizadorId")
                        .HasColumnType("int");

                    b.Property<bool>("PermiteImpedimentos")
                        .HasColumnType("bit");

                    b.Property<decimal>("PrecoInscricao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantidadeQuadras")
                        .HasColumnType("int");

                    b.Property<int>("SetsFaseFinal")
                        .HasColumnType("int");

                    b.Property<int>("SetsFaseGrupos")
                        .HasColumnType("int");

                    b.Property<int>("SetsFaseMataMata")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TamanhoGrupo")
                        .HasColumnType("int");

                    b.Property<int>("TempoPrevistoPartidaMinutos")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Torneio__3214EC072B430D79");

                    b.HasIndex("ClubeId");

                    b.HasIndex("OrganizadorId");

                    b.HasIndex(new[] { "Codigo" }, "UQ__Torneio__06370DAC1187A52A")
                        .IsUnique();

                    b.ToTable("Torneio", (string)null);
                });

            modelBuilder.Entity("Padelizou.Models.TorneioOrganizador", b =>
                {
                    b.Property<int>("TorneioId")
                        .HasColumnType("int");

                    b.Property<int>("JogadorId")
                        .HasColumnType("int");

                    b.Property<string>("NivelAcesso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TorneioId", "JogadorId");

                    b.HasIndex("JogadorId");

                    b.ToTable("TorneioOrganizador");
                });

            modelBuilder.Entity("padelizou.Models.Aula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoogleEventId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocalAulaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TokenConfirmacao")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("LocalAulaId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("TokenConfirmacao")
                        .IsUnique();

                    b.ToTable("Aula");
                });

            modelBuilder.Entity("padelizou.Models.CategoriaPadrao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoriaPadrao");
                });

            modelBuilder.Entity("padelizou.Models.GrupoPrivado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdministradorId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoConvite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId");

                    b.ToTable("GrupoPrivado");
                });

            modelBuilder.Entity("padelizou.Models.GrupoTorneio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TorneioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("TorneioId");

                    b.ToTable("GrupoTorneio");
                });

            modelBuilder.Entity("padelizou.Models.JogadorGrupo", b =>
                {
                    b.Property<int>("JogadorId")
                        .HasColumnType("int");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<int>("PontuacaoInterna")
                        .HasColumnType("int");

                    b.HasKey("JogadorId", "GrupoId");

                    b.HasIndex("GrupoId");

                    b.ToTable("JogadorGrupo");
                });

            modelBuilder.Entity("Padelizou.Models.AvisoJogo", b =>
                {
                    b.HasOne("padelizou.Models.CategoriaPadrao", "CategoriaPadrao")
                        .WithMany()
                        .HasForeignKey("CategoriaPadraoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Clube", "Clube")
                        .WithMany()
                        .HasForeignKey("ClubeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Criador")
                        .WithMany()
                        .HasForeignKey("CriadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaPadrao");

                    b.Navigation("Clube");

                    b.Navigation("Criador");
                });

            modelBuilder.Entity("Padelizou.Models.AvisoParceiro", b =>
                {
                    b.HasOne("Padelizou.Models.Jogador", "Criador")
                        .WithMany()
                        .HasForeignKey("CriadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criador");
                });

            modelBuilder.Entity("Padelizou.Models.CandidaturaParceiro", b =>
                {
                    b.HasOne("Padelizou.Models.AvisoParceiro", "AvisoParceiro")
                        .WithMany("Candidaturas")
                        .HasForeignKey("AvisoParceiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Candidato")
                        .WithMany()
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AvisoParceiro");

                    b.Navigation("Candidato");
                });

            modelBuilder.Entity("Padelizou.Models.Categoria", b =>
                {
                    b.HasOne("Padelizou.Models.Torneio", "Torneio")
                        .WithMany("Categorias")
                        .HasForeignKey("TorneioId")
                        .IsRequired()
                        .HasConstraintName("FK__Categoria__Torne__5165187F");

                    b.Navigation("Torneio");
                });

            modelBuilder.Entity("Padelizou.Models.Dupla", b =>
                {
                    b.HasOne("Padelizou.Models.Categoria", "Categoria")
                        .WithMany("Duplas")
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK__Dupla__Categoria__571DF1D5");

                    b.HasOne("padelizou.Models.GrupoTorneio", "GrupoTorneio")
                        .WithMany("Duplas")
                        .HasForeignKey("GrupoTorneioId");

                    b.HasOne("Padelizou.Models.Jogador", "Jogador1")
                        .WithMany("DuplaJogador1s")
                        .HasForeignKey("Jogador1Id")
                        .IsRequired()
                        .HasConstraintName("FK__Dupla__Jogador1I__5812160E");

                    b.HasOne("Padelizou.Models.Jogador", "Jogador2")
                        .WithMany("DuplaJogador2s")
                        .HasForeignKey("Jogador2Id")
                        .IsRequired()
                        .HasConstraintName("FK__Dupla__Jogador2I__59063A47");

                    b.HasOne("Padelizou.Models.Torneio", "Torneio")
                        .WithMany()
                        .HasForeignKey("TorneioId");

                    b.Navigation("Categoria");

                    b.Navigation("GrupoTorneio");

                    b.Navigation("Jogador1");

                    b.Navigation("Jogador2");

                    b.Navigation("Torneio");
                });

            modelBuilder.Entity("Padelizou.Models.HorarioDisponivel", b =>
                {
                    b.HasOne("Padelizou.Models.LocalAula", "LocalAula")
                        .WithMany("Horarios")
                        .HasForeignKey("LocalAulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LocalAula");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Padelizou.Models.Jogador", b =>
                {
                    b.HasOne("Padelizou.Models.Time", "Time")
                        .WithMany("Jogadores")
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Time");
                });

            modelBuilder.Entity("Padelizou.Models.JogadorCategoria", b =>
                {
                    b.HasOne("padelizou.Models.CategoriaPadrao", "CategoriaPadrao")
                        .WithMany()
                        .HasForeignKey("CategoriaPadraoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Jogador")
                        .WithMany("JogadorCategorias")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaPadrao");

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("Padelizou.Models.JogadorClube", b =>
                {
                    b.HasOne("Padelizou.Models.Clube", "Clube")
                        .WithMany()
                        .HasForeignKey("ClubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Jogador")
                        .WithMany("JogadorClubes")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clube");

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("Padelizou.Models.JogadorDiaHorario", b =>
                {
                    b.HasOne("Padelizou.Models.Jogador", "Jogador")
                        .WithMany("JogadorDiasHorarios")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("Padelizou.Models.JogoSemanal", b =>
                {
                    b.HasOne("Padelizou.Models.Jogador", "Dupla1Jogador1")
                        .WithMany()
                        .HasForeignKey("Dupla1Jogador1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Dupla1Jogador2")
                        .WithMany()
                        .HasForeignKey("Dupla1Jogador2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Dupla2Jogador1")
                        .WithMany()
                        .HasForeignKey("Dupla2Jogador1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Dupla2Jogador2")
                        .WithMany()
                        .HasForeignKey("Dupla2Jogador2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("padelizou.Models.GrupoPrivado", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dupla1Jogador1");

                    b.Navigation("Dupla1Jogador2");

                    b.Navigation("Dupla2Jogador1");

                    b.Navigation("Dupla2Jogador2");

                    b.Navigation("Grupo");

                    b.Navigation("RegistradoPor");
                });

            modelBuilder.Entity("Padelizou.Models.LocalAula", b =>
                {
                    b.HasOne("Padelizou.Models.Jogador", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Padelizou.Models.Partida", b =>
                {
                    b.HasOne("Padelizou.Models.Categoria", "Categoria")
                        .WithMany("Partidas")
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK__Partida__Categor__5FB337D6");

                    b.HasOne("Padelizou.Models.Dupla", "Dupla1")
                        .WithMany("PartidasDupla1")
                        .HasForeignKey("Dupla1Id")
                        .IsRequired()
                        .HasConstraintName("FK__Partida__Dupla1I__60A75C0F");

                    b.HasOne("Padelizou.Models.Dupla", "Dupla2")
                        .WithMany("PartidasDupla2")
                        .HasForeignKey("Dupla2Id")
                        .IsRequired()
                        .HasConstraintName("FK__Partida__Dupla2I__619B8048");

                    b.Navigation("Categoria");

                    b.Navigation("Dupla1");

                    b.Navigation("Dupla2");
                });

            modelBuilder.Entity("Padelizou.Models.Time", b =>
                {
                    b.HasOne("Padelizou.Models.Clube", "Clube")
                        .WithMany("Times")
                        .HasForeignKey("ClubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clube");
                });

            modelBuilder.Entity("Padelizou.Models.Torneio", b =>
                {
                    b.HasOne("Padelizou.Models.Clube", "Clube")
                        .WithMany("Torneios")
                        .HasForeignKey("ClubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Organizador", "Organizador")
                        .WithMany("Torneios")
                        .HasForeignKey("OrganizadorId")
                        .IsRequired()
                        .HasConstraintName("FK__Torneio__Organiz__4E88ABD4");

                    b.Navigation("Clube");

                    b.Navigation("Organizador");
                });

            modelBuilder.Entity("Padelizou.Models.TorneioOrganizador", b =>
                {
                    b.HasOne("Padelizou.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Torneio", "Torneio")
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");

                    b.Navigation("Torneio");
                });

            modelBuilder.Entity("padelizou.Models.Aula", b =>
                {
                    b.HasOne("Padelizou.Models.Jogador", "Aluno")
                        .WithMany("AulasRecebidas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.LocalAula", "LocalAula")
                        .WithMany()
                        .HasForeignKey("LocalAulaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Professor")
                        .WithMany("AulasDadas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("LocalAula");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("padelizou.Models.GrupoPrivado", b =>
                {
                    b.HasOne("Padelizou.Models.Jogador", "Administrador")
                        .WithMany()
                        .HasForeignKey("AdministradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Administrador");
                });

            modelBuilder.Entity("padelizou.Models.GrupoTorneio", b =>
                {
                    b.HasOne("Padelizou.Models.Categoria", "Categoria")
                        .WithMany("GruposTorneio")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Torneio", null)
                        .WithMany("GruposTorneio")
                        .HasForeignKey("TorneioId");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("padelizou.Models.JogadorGrupo", b =>
                {
                    b.HasOne("padelizou.Models.GrupoPrivado", "GrupoPrivado")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoPrivado");

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("Padelizou.Models.AvisoParceiro", b =>
                {
                    b.Navigation("Candidaturas");
                });

            modelBuilder.Entity("Padelizou.Models.Categoria", b =>
                {
                    b.Navigation("Duplas");

                    b.Navigation("GruposTorneio");

                    b.Navigation("Partidas");
                });

            modelBuilder.Entity("Padelizou.Models.Clube", b =>
                {
                    b.Navigation("Times");

                    b.Navigation("Torneios");
                });

            modelBuilder.Entity("Padelizou.Models.Dupla", b =>
                {
                    b.Navigation("PartidasDupla1");

                    b.Navigation("PartidasDupla2");
                });

            modelBuilder.Entity("Padelizou.Models.Jogador", b =>
                {
                    b.Navigation("AulasDadas");

                    b.Navigation("AulasRecebidas");

                    b.Navigation("DuplaJogador1s");

                    b.Navigation("DuplaJogador2s");

                    b.Navigation("JogadorCategorias");

                    b.Navigation("JogadorClubes");

                    b.Navigation("JogadorDiasHorarios");
                });

            modelBuilder.Entity("Padelizou.Models.LocalAula", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("Padelizou.Models.Organizador", b =>
                {
                    b.Navigation("Torneios");
                });

            modelBuilder.Entity("Padelizou.Models.Time", b =>
                {
                    b.Navigation("Jogadores");
                });

            modelBuilder.Entity("Padelizou.Models.Torneio", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("GruposTorneio");
                });

            modelBuilder.Entity("padelizou.Models.GrupoTorneio", b =>
                {
                    b.Navigation("Duplas");
                });
#pragma warning restore 612, 618
        }
    }
}
