// Textos do questionário de 3 perguntas (src/ui/screens/survey.ts). Os ids das respostas (again 1–5, difficulty,
// hurdle) são o contrato com o diário (src/game/playlog.ts); aqui só a redação, que o dono pode trocar.
import { registerStrings } from '../i18n';

registerStrings('playlog', {
  pt: {
    'survey.title': 'Três perguntas rápidas',
    'survey.note': 'As respostas ficam neste computador e vão no relatório que você nos mandar.',
    'survey.again': 'Jogaria de novo amanhã?',
    'survey.again.1': '1 · Não',
    'survey.again.2': '2',
    'survey.again.3': '3 · Talvez',
    'survey.again.4': '4',
    'survey.again.5': '5 · Com certeza',
    'survey.difficulty': 'A dificuldade estava…',
    'survey.difficulty.easy': 'Fácil demais',
    'survey.difficulty.right': 'No ponto',
    'survey.difficulty.hard': 'Difícil demais',
    'survey.hurdle': 'O que mais atrapalhou?',
    'survey.hurdle.none': 'Nada',
    'survey.hurdle.menus': 'Os menus',
    'survey.hurdle.controls': 'Os controles',
    'survey.hurdle.seeing': 'Enxergar a pista',
    'survey.hurdle.performance': 'O jogo travando',
    'survey.hurdle.other': 'Outra coisa',
    'survey.unanswered': '—',
    'survey.save': 'Salvar respostas',
    'survey.skip': 'Pular',
  },
  en: {
    'survey.title': 'Three quick questions',
    'survey.note': 'Your answers stay on this computer and go in the report you send us.',
    'survey.again': 'Would you play again tomorrow?',
    'survey.again.1': '1 · No',
    'survey.again.2': '2',
    'survey.again.3': '3 · Maybe',
    'survey.again.4': '4',
    'survey.again.5': '5 · Definitely',
    'survey.difficulty': 'The difficulty was…',
    'survey.difficulty.easy': 'Too easy',
    'survey.difficulty.right': 'Just right',
    'survey.difficulty.hard': 'Too hard',
    'survey.hurdle': 'What got in the way the most?',
    'survey.hurdle.none': 'Nothing',
    'survey.hurdle.menus': 'The menus',
    'survey.hurdle.controls': 'The controls',
    'survey.hurdle.seeing': 'Seeing the track',
    'survey.hurdle.performance': 'The game stuttering',
    'survey.hurdle.other': 'Something else',
    'survey.unanswered': '—',
    'survey.save': 'Save answers',
    'survey.skip': 'Skip',
  },
});
