// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Padelizou.Models;

#nullable disable

namespace Padelizou.Migrations
{
    [DbContext(typeof(DbPadelContext))]
    [Migration("20260727143601_FormaPagamentoDoTorneio")]
    partial class FormaPagamentoDoTorneio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Padelizou.Models.AlertaSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EnviadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AlertaSistema");
                });

            modelBuilder.Entity("Padelizou.Models.AvaliacaoProfessor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Depoimento")
                        .HasColumnType("text");

                    b.Property<int>("Nota")
                        .HasColumnType("integer");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("AlunoId", "ProfessorId")
                        .IsUnique();

                    b.ToTable("AvaliacaoProfessor");
                });

            modelBuilder.Entity("Padelizou.Models.AvisoJogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaPadraoId")
                        .HasColumnType("integer");

                    b.Property<int>("ClubeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CriadorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPadraoId");

                    b.HasIndex("ClubeId");

                    b.HasIndex("CriadorId");

                    b.ToTable("AvisoJogo");
                });

            modelBuilder.Entity("Padelizou.Models.AvisoParceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CriadorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeTorneio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CriadorId");

                    b.ToTable("AvisoParceiro");
                });

            modelBuilder.Entity("Padelizou.Models.AvisoRaqueteLivre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CriadorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataHoraFim")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataHoraInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("LimiteVagas")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<decimal?>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClubeId");

                    b.HasIndex("CriadorId");

                    b.ToTable("AvisoRaqueteLivre");
                });

            modelBuilder.Entity("Padelizou.Models.CandidaturaParceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AvisoParceiroId")
                        .HasColumnType("integer");

                    b.Property<int>("CandidatoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AvisoParceiroId");

                    b.HasIndex("CandidatoId");

                    b.ToTable("CandidaturaParceiro");
                });

            modelBuilder.Entity("Padelizou.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("LimiteDuplas")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TorneioId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC079FE58FF8");

                    b.HasIndex("TorneioId");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Padelizou.Models.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cidades");
                });

            modelBuilder.Entity("Padelizou.Models.Clube", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CidadeId")
                        .HasColumnType("integer");

                    b.Property<bool>("CobraNoShow")
                        .HasColumnType("boolean");

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DonoId")
                        .HasColumnType("integer");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HorasMinimasCancelamento")
                        .HasColumnType("integer");

                    b.Property<bool>("MarcacaoHorariosAtiva")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("NotificarHorariosDiariamente")
                        .HasColumnType("boolean");

                    b.Property<string>("PoliticaCancelamentoTexto")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.HasIndex("DonoId");

                    b.ToTable("Clubes");
                });

            modelBuilder.Entity("Padelizou.Models.ClubeAdministrador", b =>
                {
                    b.Property<int>("ClubeId")
                        .HasColumnType("integer");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AdicionadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ClubeId", "JogadorId");

                    b.HasIndex("JogadorId");

                    b.ToTable("ClubeAdministrador");
                });

            modelBuilder.Entity("Padelizou.Models.ComentarioPerfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PerfilId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("PerfilId");

                    b.ToTable("ComentariosPerfil");
                });

            modelBuilder.Entity("Padelizou.Models.ConfirmacaoSessao", b =>
                {
                    b.Property<int>("SessaoId")
                        .HasColumnType("integer");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer");

                    b.Property<bool>("Avulso")
                        .HasColumnType("boolean");

                    b.Property<string>("Lado")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LembreteEnviadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("RespondidoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SessaoId", "JogadorId");

                    b.HasIndex("JogadorId");

                    b.ToTable("ConfirmacaoSessao");
                });

            modelBuilder.Entity("Padelizou.Models.Dupla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CheckInEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("EmListaDeEspera")
                        .HasColumnType("boolean");

                    b.Property<string>("Grupo")
                        .HasColumnType("text");

                    b.Property<int?>("GrupoTorneioId")
                        .HasColumnType("integer");

                    b.Property<bool>("ImpedimentoSabadoManha")
                        .HasColumnType("boolean");

                    b.Property<bool>("ImpedimentoSabadoTarde")
                        .HasColumnType("boolean");

                    b.Property<bool>("ImpedimentoSextaNoite")
                        .HasColumnType("boolean");

                    b.Property<int>("Jogador1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Jogador2Id")
                        .HasColumnType("integer");

                    b.Property<string>("UltimaFase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK__Dupla__3214EC07E192F96C");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("GrupoTorneioId");

                    b.HasIndex("Jogador1Id");

                    b.HasIndex("Jogador2Id");

                    b.ToTable("Dupla", (string)null);
                });

            modelBuilder.Entity("Padelizou.Models.Elogio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DeJogadorId")
                        .HasColumnType("integer");

                    b.Property<int>("ParaJogadorId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParaJogadorId");

                    b.HasIndex("DeJogadorId", "ParaJogadorId", "Tipo")
                        .IsUnique();

                    b.ToTable("Elogios");
                });

            modelBuilder.Entity("Padelizou.Models.HorarioDisponivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<int>("LocalAulaId")
                        .HasColumnType("integer");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocalAulaId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("HorarioDisponivel");
                });

            modelBuilder.Entity("Padelizou.Models.HorarioMarcacaoDisponivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<int>("ClubeId")
                        .HasColumnType("integer");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("HoraFim")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<decimal?>("Preco")
                        .HasColumnType("numeric");

                    b.Property<int>("QuadraClubeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClubeId");

                    b.HasIndex("QuadraClubeId");

                    b.ToTable("HorarioMarcacaoDisponivel");
                });

            modelBuilder.Entity("Padelizou.Models.InscricaoAmericana", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("EmListaDeEspera")
                        .HasColumnType("boolean");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("JogadorId");

                    b.ToTable("InscricaoAmericana");
                });

            modelBuilder.Entity("Padelizou.Models.InscricaoRaqueteLivre", b =>
                {
                    b.Property<int>("AvisoRaqueteLivreId")
                        .HasColumnType("integer");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer");

                    b.Property<bool>("EmListaDeEspera")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("InscritoEm")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("AvisoRaqueteLivreId", "JogadorId");

                    b.HasIndex("JogadorId");

                    b.ToTable("InscricaoRaqueteLivre");
                });

            modelBuilder.Entity("Padelizou.Models.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AceitaConvitesJogo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("AgendaFeedToken")
                        .HasColumnType("uuid");

                    b.Property<bool>("AgendaMostrarAlunos")
                        .HasColumnType("boolean");

                    b.Property<bool>("AgendaMostrarAulas")
                        .HasColumnType("boolean");

                    b.Property<bool>("AgendaMostrarJogosSemanais")
                        .HasColumnType("boolean");

                    b.Property<bool>("AgendaMostrarMarcacoes")
                        .HasColumnType("boolean");

                    b.Property<bool>("AgendaMostrarTorneios")
                        .HasColumnType("boolean");

                    b.Property<string>("Apelido")
                        .HasColumnType("text");

                    b.Property<string>("ApresentacaoProfessor")
                        .HasColumnType("text");

                    b.Property<string>("AsaasWalletId")
                        .HasColumnType("text");

                    b.Property<string>("Celular")
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<bool>("CobraFaltaSemAviso")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("CPF");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<string>("ExperienciaProfessor")
                        .HasColumnType("text");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("text");

                    b.Property<int>("HorasMinimasCancelamento")
                        .HasColumnType("integer");

                    b.Property<string>("Instagram")
                        .HasColumnType("text");

                    b.Property<bool>("IsAdminGeral")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdminRaiz")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProfessor")
                        .HasColumnType("boolean");

                    b.Property<string>("LadoQuadra")
                        .HasColumnType("text");

                    b.Property<string>("Lateralidade")
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ModoComissao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("NotificarAvisoJogo")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotificarEmail")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotificarHorarioVagoRegiao")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotificarJogoAula")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotificarRaqueteLivre")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotificarSeguidosTorneio")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotificarTorneiosAbertos")
                        .HasColumnType("boolean");

                    b.Property<bool>("NotificarWhatsApp")
                        .HasColumnType("boolean");

                    b.Property<bool>("PerfilPrivado")
                        .HasColumnType("boolean");

                    b.Property<string>("PoliticaCancelamentoTexto")
                        .HasColumnType("text");

                    b.Property<int>("PontuacaoGlobal")
                        .HasColumnType("integer");

                    b.Property<bool>("ReceberPagamentoOnline")
                        .HasColumnType("boolean");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("text");

                    b.Property<int?>("TimeId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK__Jogador__3214EC07E9B77CE2");

                    b.HasIndex("AgendaFeedToken")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("TimeId");

                    b.HasIndex(new[] { "Cpf" }, "UQ__Jogador__C1F897318C6002EF")
                        .IsUnique();

                    b.ToTable("Jogador", (string)null);
                });

            modelBuilder.Entity("Padelizou.Models.JogadorCategoria", b =>
                {
                    b.Property<int>("JogadorId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoriaPadraoId")
                        .HasColumnType("integer");

                    b.HasKey("JogadorId", "CategoriaPadraoId");

                    b.HasIndex("CategoriaPadraoId");

                    b.ToTable("JogadorCategoria");
                });

            modelBuilder.Entity("Padelizou.Models.JogadorCidade", b =>
                {
                    b.Property<int>("JogadorId")
                        .HasColumnType("integer");

                    b.Property<int>("CidadeId")
                        .HasColumnType("integer");

                    b.HasKey("JogadorId", "CidadeId");

                    b.HasIndex("CidadeId");

                    b.ToTable("JogadorCidade");
                });

            modelBuilder.Entity("Padelizou.Models.JogadorClube", b =>
                {
                    b.Property<int>("JogadorId")
                        .HasColumnType("integer");

                    b.Property<int>("ClubeId")
                        .HasColumnType("integer");

                    b.HasKey("JogadorId", "ClubeId");

                    b.HasIndex("ClubeId");

                    b.ToTable("JogadorClube");
                });

            modelBuilder.Entity("Padelizou.Models.JogadorDiaHorario", b =>
                {
                    b.Property<int>("JogadorId")
                        .HasColumnType("integer");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<string>("Periodo")
                        .HasColumnType("text");

                    b.HasKey("JogadorId", "DiaSemana", "Periodo");

                    b.ToTable("JogadorDiaHorario");
                });

            modelBuilder.Entity("Padelizou.Models.JogoSemanal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataJogo")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Dupla1Jogador1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Dupla1Jogador2Id")
                        .HasColumnType("integer");

                    b.Property<int>("Dupla2Jogador1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Dupla2Jogador2Id")
                        .HasColumnType("integer");

                    b.Property<int>("GamesDupla1")
                        .HasColumnType("integer");

                    b.Property<int>("GamesDupla2")
                        .HasColumnType("integer");

                    b.Property<int>("GrupoId")
                        .HasColumnType("integer");

                    b.Property<int>("RegistradoPorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Dupla1Jogador1Id");

                    b.HasIndex("Dupla1Jogador2Id");

                    b.HasIndex("Dupla2Jogador1Id");

                    b.HasIndex("Dupla2Jogador2Id");

                    b.HasIndex("GrupoId");

                    b.HasIndex("RegistradoPorId");

                    b.ToTable("JogoSemanal");
                });

            modelBuilder.Entity("Padelizou.Models.LocalAula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("CustoPorAula")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PacoteAtivo")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("PacotePreco")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("PacoteQuantidadeAulas")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecoPadrao")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("LocalAula");
                });

            modelBuilder.Entity("Padelizou.Models.MarcacaoJogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CanceladaEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CanceladaPor")
                        .HasColumnType("text");

                    b.Property<int>("ClubeId")
                        .HasColumnType("integer");

                    b.Property<bool>("CobrarMesmoAssim")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DuracaoMinutos")
                        .HasColumnType("integer");

                    b.Property<bool>("EhBloqueio")
                        .HasColumnType("boolean");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MensalidadeId")
                        .HasColumnType("uuid");

                    b.Property<string>("MotivoBloqueio")
                        .HasColumnType("text");

                    b.Property<int>("QuadraClubeId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClubeId");

                    b.HasIndex("JogadorId");

                    b.HasIndex("QuadraClubeId");

                    b.ToTable("MarcacaoJogo");
                });

            modelBuilder.Entity("Padelizou.Models.MensalidadeGrupo", b =>
                {
                    b.Property<int>("GrupoId")
                        .HasColumnType("integer");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer");

                    b.Property<int>("Ano")
                        .HasColumnType("integer");

                    b.Property<int>("Mes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Pago")
                        .HasColumnType("boolean");

                    b.HasKey("GrupoId", "JogadorId", "Ano", "Mes");

                    b.HasIndex("JogadorId");

                    b.ToTable("MensalidadeGrupo");
                });

            modelBuilder.Entity("Padelizou.Models.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AsaasCustomerId")
                        .HasColumnType("text");

                    b.Property<string>("AsaasPaymentId")
                        .HasColumnType("text");

                    b.Property<decimal>("Comissao")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ConfirmadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DadosInscricao")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiraEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InvoiceUrl")
                        .HasColumnType("text");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer");

                    b.Property<int?>("JogoAulaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LembreteEnviadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("RecebedorId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReferenciaId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TorneioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorRepasse")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AsaasPaymentId");

                    b.HasIndex("JogadorId");

                    b.ToTable("Pagamento");
                });

            modelBuilder.Entity("Padelizou.Models.PalpitePartida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DuplaEscolhidaId")
                        .HasColumnType("integer");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer");

                    b.Property<int>("PartidaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DuplaEscolhidaId");

                    b.HasIndex("JogadorId");

                    b.HasIndex("PartidaId", "JogadorId")
                        .IsUnique();

                    b.ToTable("PalpitePartida");
                });

            modelBuilder.Entity("Padelizou.Models.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Dupla1Id")
                        .HasColumnType("integer");

                    b.Property<int>("Dupla2Id")
                        .HasColumnType("integer");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("GamesDupla1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("GamesDupla2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("HorarioFimReal")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("HorarioInicioReal")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("HorarioPrevisto")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LinkTransmissao")
                        .HasColumnType("text");

                    b.Property<string>("NomeQuadra")
                        .HasColumnType("text");

                    b.Property<bool>("SendoTransmitida")
                        .HasColumnType("boolean");

                    b.Property<int?>("SetsDupla1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("SetsDupla2")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TorneioId")
                        .HasColumnType("integer");

                    b.Property<int?>("VencedorId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK__Partida__3214EC0755DC2078");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Dupla1Id");

                    b.HasIndex("Dupla2Id");

                    b.ToTable("Partida");
                });

            modelBuilder.Entity("Padelizou.Models.ProfessorCidade", b =>
                {
                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer");

                    b.Property<int>("CidadeId")
                        .HasColumnType("integer");

                    b.HasKey("ProfessorId", "CidadeId");

                    b.HasIndex("CidadeId");

                    b.ToTable("ProfessorCidade");
                });

            modelBuilder.Entity("Padelizou.Models.PushSubscriptionJogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.HasIndex("JogadorId");

                    b.ToTable("PushSubscriptionJogador");
                });

            modelBuilder.Entity("Padelizou.Models.Quadra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TorneioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TorneioId");

                    b.ToTable("Quadra");
                });

            modelBuilder.Entity("Padelizou.Models.QuadraClube", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean");

                    b.Property<int>("ClubeId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClubeId");

                    b.ToTable("QuadraClube");
                });

            modelBuilder.Entity("Padelizou.Models.SeguidorJogador", b =>
                {
                    b.Property<int>("SeguidorId")
                        .HasColumnType("integer");

                    b.Property<int>("SeguidoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("SeguidorId", "SeguidoId");

                    b.HasIndex("SeguidoId");

                    b.ToTable("SeguidorJogador");
                });

            modelBuilder.Entity("Padelizou.Models.SessaoGrupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("GrupoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GrupoId", "DataHora")
                        .IsUnique();

                    b.ToTable("SessaoGrupo");
                });

            modelBuilder.Entity("Padelizou.Models.Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClubeId")
                        .HasColumnType("integer");

                    b.Property<int?>("DonoId")
                        .HasColumnType("integer");

                    b.Property<string>("Logo")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClubeId");

                    b.ToTable("Times");
                });

            modelBuilder.Entity("Padelizou.Models.Torneio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("BloquearCategoriaInferior")
                        .HasColumnType("boolean");

                    b.Property<string>("ChaveAcesso")
                        .HasColumnType("text");

                    b.Property<int>("ClassificadosPorGrupo")
                        .HasColumnType("integer");

                    b.Property<int>("ClubeId")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("FormatoUnico")
                        .HasColumnType("boolean");

                    b.Property<int>("GamesFaseFinal")
                        .HasColumnType("integer");

                    b.Property<int>("GamesFaseGrupos")
                        .HasColumnType("integer");

                    b.Property<int>("GamesFaseMataMata")
                        .HasColumnType("integer");

                    b.Property<string>("ImagemCapa")
                        .HasColumnType("text");

                    b.Property<int?>("LimiteDuplasTotal")
                        .HasColumnType("integer");

                    b.Property<string>("LocalTorneio")
                        .HasColumnType("text");

                    b.Property<string>("ModoComissao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("Oculto")
                        .HasColumnType("boolean");

                    b.Property<bool>("PermiteImpedimentoSabadoManha")
                        .HasColumnType("boolean");

                    b.Property<bool>("PermiteImpedimentoSabadoTarde")
                        .HasColumnType("boolean");

                    b.Property<bool>("PermiteImpedimentoSextaNoite")
                        .HasColumnType("boolean");

                    b.Property<bool>("PermiteImpedimentos")
                        .HasColumnType("boolean");

                    b.Property<bool>("PermiteMultiplasCategorias")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PrecoInscricao")
                        .HasColumnType("numeric");

                    b.Property<int>("QuantidadeQuadras")
                        .HasColumnType("integer");

                    b.Property<string>("RestricaoCategoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Restrito")
                        .HasColumnType("boolean");

                    b.Property<int>("SetsFaseFinal")
                        .HasColumnType("integer");

                    b.Property<int>("SetsFaseGrupos")
                        .HasColumnType("integer");

                    b.Property<int>("SetsFaseMataMata")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TamanhoGrupo")
                        .HasColumnType("integer");

                    b.Property<int>("TempoPrevistoPartidaMinutos")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK__Torneio__3214EC072B430D79");

                    b.HasIndex("ClubeId");

                    b.HasIndex(new[] { "Codigo" }, "UQ__Torneio__06370DAC1187A52A")
                        .IsUnique();

                    b.ToTable("Torneio", (string)null);
                });

            modelBuilder.Entity("Padelizou.Models.TorneioOrganizador", b =>
                {
                    b.Property<int>("TorneioId")
                        .HasColumnType("integer");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer");

                    b.Property<string>("NivelAcesso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TorneioId", "JogadorId");

                    b.HasIndex("JogadorId");

                    b.ToTable("TorneioOrganizador");
                });

            modelBuilder.Entity("padelizou.Models.Aula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlunoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CanceladaEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CanceladaPor")
                        .HasColumnType("text");

                    b.Property<bool>("CobrarMesmoFaltando")
                        .HasColumnType("boolean");

                    b.Property<bool?>("Compareceu")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("GoogleEventId")
                        .HasColumnType("text");

                    b.Property<int?>("HorasDeAntecedenciaCancelamento")
                        .HasColumnType("integer");

                    b.Property<int>("LocalAulaId")
                        .HasColumnType("integer");

                    b.Property<string>("NomeAlunoAvulso")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RecorrenciaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelefoneAlunoAvulso")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TokenConfirmacao")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("LocalAulaId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("TokenConfirmacao")
                        .IsUnique();

                    b.ToTable("Aula");
                });

            modelBuilder.Entity("padelizou.Models.CategoriaPadrao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CategoriaPadrao");
                });

            modelBuilder.Entity("padelizou.Models.GrupoPrivado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdministradorId")
                        .HasColumnType("integer");

                    b.Property<int?>("CategoriaPadraoId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClubeId")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoConvite")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DiaSemanaFixo")
                        .HasColumnType("integer");

                    b.Property<bool>("EnviarLembrete24h")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<TimeSpan?>("HorarioFixo")
                        .HasColumnType("interval");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VagasMaximas")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ValorAvulso")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ValorMensalidade")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId");

                    b.HasIndex("CategoriaPadraoId");

                    b.HasIndex("ClubeId");

                    b.ToTable("GrupoPrivado");
                });

            modelBuilder.Entity("padelizou.Models.GrupoTorneio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("GrupoTorneio");
                });

            modelBuilder.Entity("padelizou.Models.InscricaoJogoAula", b =>
                {
                    b.Property<int>("JogoAulaId")
                        .HasColumnType("integer");

                    b.Property<int>("JogadorId")
                        .HasColumnType("integer");

                    b.Property<bool>("EmListaDeEspera")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("InscritoEm")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("JogoAulaId", "JogadorId");

                    b.HasIndex("JogadorId");

                    b.ToTable("InscricaoJogoAula");
                });

            modelBuilder.Entity("padelizou.Models.JogadorGrupo", b =>
                {
                    b.Property<int>("JogadorId")
                        .HasColumnType("integer");

                    b.Property<int>("GrupoId")
                        .HasColumnType("integer");

                    b.Property<int>("PontuacaoInterna")
                        .HasColumnType("integer");

                    b.HasKey("JogadorId", "GrupoId");

                    b.HasIndex("GrupoId");

                    b.ToTable("JogadorGrupo");
                });

            modelBuilder.Entity("padelizou.Models.JogoAula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaPadraoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("LimiteVagas")
                        .HasColumnType("integer");

                    b.Property<int>("LocalAulaId")
                        .HasColumnType("integer");

                    b.Property<string>("Modalidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<decimal?>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPadraoId");

                    b.HasIndex("LocalAulaId");

                    b.HasIndex("ProfessorId");

                    b.ToTable("JogoAula");
                });

            modelBuilder.Entity("Padelizou.Models.AvaliacaoProfessor", b =>
                {
                    b.HasOne("Padelizou.Models.Jogador", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Padelizou.Models.AvisoJogo", b =>
                {
                    b.HasOne("padelizou.Models.CategoriaPadrao", "CategoriaPadrao")
                        .WithMany()
                        .HasForeignKey("CategoriaPadraoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Clube", "Clube")
                        .WithMany()
                        .HasForeignKey("ClubeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Criador")
                        .WithMany()
                        .HasForeignKey("CriadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaPadrao");

                    b.Navigation("Clube");

                    b.Navigation("Criador");
                });

            modelBuilder.Entity("Padelizou.Models.AvisoParceiro", b =>
                {
                    b.HasOne("Padelizou.Models.Jogador", "Criador")
                        .WithMany()
                        .HasForeignKey("CriadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criador");
                });

            modelBuilder.Entity("Padelizou.Models.AvisoRaqueteLivre", b =>
                {
                    b.HasOne("Padelizou.Models.Clube", "Clube")
                        .WithMany()
                        .HasForeignKey("ClubeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Criador")
                        .WithMany()
                        .HasForeignKey("CriadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clube");

                    b.Navigation("Criador");
                });

            modelBuilder.Entity("Padelizou.Models.CandidaturaParceiro", b =>
                {
                    b.HasOne("Padelizou.Models.AvisoParceiro", "AvisoParceiro")
                        .WithMany("Candidaturas")
                        .HasForeignKey("AvisoParceiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Candidato")
                        .WithMany()
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AvisoParceiro");

                    b.Navigation("Candidato");
                });

            modelBuilder.Entity("Padelizou.Models.Categoria", b =>
                {
                    b.HasOne("Padelizou.Models.Torneio", "Torneio")
                        .WithMany("Categorias")
                        .HasForeignKey("TorneioId")
                        .IsRequired()
                        .HasConstraintName("FK__Categoria__Torne__5165187F");

                    b.Navigation("Torneio");
                });

            modelBuilder.Entity("Padelizou.Models.Clube", b =>
                {
                    b.HasOne("Padelizou.Models.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Padelizou.Models.Jogador", "Dono")
                        .WithMany()
                        .HasForeignKey("DonoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cidade");

                    b.Navigation("Dono");
                });

            modelBuilder.Entity("Padelizou.Models.ClubeAdministrador", b =>
                {
                    b.HasOne("Padelizou.Models.Clube", "Clube")
                        .WithMany()
                        .HasForeignKey("ClubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clube");

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("Padelizou.Models.ComentarioPerfil", b =>
                {
                    b.HasOne("Padelizou.Models.Jogador", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Padelizou.Models.ConfirmacaoSessao", b =>
                {
                    b.HasOne("Padelizou.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.SessaoGrupo", "Sessao")
                        .WithMany("Confirmacoes")
                        .HasForeignKey("SessaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");

                    b.Navigation("Sessao");
                });

            modelBuilder.Entity("Padelizou.Models.Dupla", b =>
                {
                    b.HasOne("Padelizou.Models.Categoria", "Categoria")
                        .WithMany("Duplas")
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK__Dupla__Categoria__571DF1D5");

                    b.HasOne("padelizou.Models.GrupoTorneio", "GrupoTorneio")
                        .WithMany("Duplas")
                        .HasForeignKey("GrupoTorneioId");

                    b.HasOne("Padelizou.Models.Jogador", "Jogador1")
                        .WithMany("DuplaJogador1s")
                        .HasForeignKey("Jogador1Id")
                        .IsRequired()
                        .HasConstraintName("FK__Dupla__Jogador1I__5812160E");

                    b.HasOne("Padelizou.Models.Jogador", "Jogador2")
                        .WithMany("DuplaJogador2s")
                        .HasForeignKey("Jogador2Id")
                        .HasConstraintName("FK__Dupla__Jogador2I__59063A47");

                    b.Navigation("Categoria");

                    b.Navigation("GrupoTorneio");

                    b.Navigation("Jogador1");

                    b.Navigation("Jogador2");
                });

            modelBuilder.Entity("Padelizou.Models.Elogio", b =>
                {
                    b.HasOne("Padelizou.Models.Jogador", "DeJogador")
                        .WithMany()
                        .HasForeignKey("DeJogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "ParaJogador")
                        .WithMany()
                        .HasForeignKey("ParaJogadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeJogador");

                    b.Navigation("ParaJogador");
                });

            modelBuilder.Entity("Padelizou.Models.HorarioDisponivel", b =>
                {
                    b.HasOne("Padelizou.Models.LocalAula", "LocalAula")
                        .WithMany("Horarios")
                        .HasForeignKey("LocalAulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LocalAula");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Padelizou.Models.HorarioMarcacaoDisponivel", b =>
                {
                    b.HasOne("Padelizou.Models.Clube", "Clube")
                        .WithMany()
                        .HasForeignKey("ClubeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.QuadraClube", "QuadraClube")
                        .WithMany()
                        .HasForeignKey("QuadraClubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clube");

                    b.Navigation("QuadraClube");
                });

            modelBuilder.Entity("Padelizou.Models.InscricaoAmericana", b =>
                {
                    b.HasOne("Padelizou.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("Padelizou.Models.InscricaoRaqueteLivre", b =>
                {
                    b.HasOne("Padelizou.Models.AvisoRaqueteLivre", "AvisoRaqueteLivre")
                        .WithMany()
                        .HasForeignKey("AvisoRaqueteLivreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AvisoRaqueteLivre");

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("Padelizou.Models.Jogador", b =>
                {
                    b.HasOne("Padelizou.Models.Time", "Time")
                        .WithMany("Jogadores")
                        .HasForeignKey("TimeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Time");
                });

            modelBuilder.Entity("Padelizou.Models.JogadorCategoria", b =>
                {
                    b.HasOne("padelizou.Models.CategoriaPadrao", "CategoriaPadrao")
                        .WithMany()
                        .HasForeignKey("CategoriaPadraoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Jogador")
                        .WithMany("JogadorCategorias")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaPadrao");

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("Padelizou.Models.JogadorCidade", b =>
                {
                    b.HasOne("Padelizou.Models.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Jogador")
                        .WithMany("JogadorCidades")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("Padelizou.Models.JogadorClube", b =>
                {
                    b.HasOne("Padelizou.Models.Clube", "Clube")
                        .WithMany()
                        .HasForeignKey("ClubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Jogador")
                        .WithMany("JogadorClubes")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clube");

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("Padelizou.Models.JogadorDiaHorario", b =>
                {
                    b.HasOne("Padelizou.Models.Jogador", "Jogador")
                        .WithMany("JogadorDiasHorarios")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("Padelizou.Models.JogoSemanal", b =>
                {
                    b.HasOne("Padelizou.Models.Jogador", "Dupla1Jogador1")
                        .WithMany()
                        .HasForeignKey("Dupla1Jogador1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Dupla1Jogador2")
                        .WithMany()
                        .HasForeignKey("Dupla1Jogador2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Dupla2Jogador1")
                        .WithMany()
                        .HasForeignKey("Dupla2Jogador1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Dupla2Jogador2")
                        .WithMany()
                        .HasForeignKey("Dupla2Jogador2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("padelizou.Models.GrupoPrivado", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dupla1Jogador1");

                    b.Navigation("Dupla1Jogador2");

                    b.Navigation("Dupla2Jogador1");

                    b.Navigation("Dupla2Jogador2");

                    b.Navigation("Grupo");

                    b.Navigation("RegistradoPor");
                });

            modelBuilder.Entity("Padelizou.Models.LocalAula", b =>
                {
                    b.HasOne("Padelizou.Models.Jogador", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Padelizou.Models.MarcacaoJogo", b =>
                {
                    b.HasOne("Padelizou.Models.Clube", "Clube")
                        .WithMany()
                        .HasForeignKey("ClubeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.QuadraClube", "QuadraClube")
                        .WithMany()
                        .HasForeignKey("QuadraClubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clube");

                    b.Navigation("Jogador");

                    b.Navigation("QuadraClube");
                });

            modelBuilder.Entity("Padelizou.Models.MensalidadeGrupo", b =>
                {
                    b.HasOne("padelizou.Models.GrupoPrivado", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grupo");

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("Padelizou.Models.Pagamento", b =>
                {
                    b.HasOne("Padelizou.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("Padelizou.Models.PalpitePartida", b =>
                {
                    b.HasOne("Padelizou.Models.Dupla", "DuplaEscolhida")
                        .WithMany()
                        .HasForeignKey("DuplaEscolhidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Partida", "Partida")
                        .WithMany()
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DuplaEscolhida");

                    b.Navigation("Jogador");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("Padelizou.Models.Partida", b =>
                {
                    b.HasOne("Padelizou.Models.Categoria", "Categoria")
                        .WithMany("Partidas")
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK__Partida__Categor__5FB337D6");

                    b.HasOne("Padelizou.Models.Dupla", "Dupla1")
                        .WithMany("PartidasDupla1")
                        .HasForeignKey("Dupla1Id")
                        .IsRequired()
                        .HasConstraintName("FK__Partida__Dupla1I__60A75C0F");

                    b.HasOne("Padelizou.Models.Dupla", "Dupla2")
                        .WithMany("PartidasDupla2")
                        .HasForeignKey("Dupla2Id")
                        .IsRequired()
                        .HasConstraintName("FK__Partida__Dupla2I__619B8048");

                    b.Navigation("Categoria");

                    b.Navigation("Dupla1");

                    b.Navigation("Dupla2");
                });

            modelBuilder.Entity("Padelizou.Models.ProfessorCidade", b =>
                {
                    b.HasOne("Padelizou.Models.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cidade");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Padelizou.Models.PushSubscriptionJogador", b =>
                {
                    b.HasOne("Padelizou.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("Padelizou.Models.Quadra", b =>
                {
                    b.HasOne("Padelizou.Models.Torneio", "Torneio")
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Torneio");
                });

            modelBuilder.Entity("Padelizou.Models.QuadraClube", b =>
                {
                    b.HasOne("Padelizou.Models.Clube", "Clube")
                        .WithMany()
                        .HasForeignKey("ClubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clube");
                });

            modelBuilder.Entity("Padelizou.Models.SeguidorJogador", b =>
                {
                    b.HasOne("Padelizou.Models.Jogador", "Seguido")
                        .WithMany()
                        .HasForeignKey("SeguidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Seguidor")
                        .WithMany()
                        .HasForeignKey("SeguidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seguido");

                    b.Navigation("Seguidor");
                });

            modelBuilder.Entity("Padelizou.Models.SessaoGrupo", b =>
                {
                    b.HasOne("padelizou.Models.GrupoPrivado", "Grupo")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("Padelizou.Models.Time", b =>
                {
                    b.HasOne("Padelizou.Models.Clube", "Clube")
                        .WithMany("Times")
                        .HasForeignKey("ClubeId");

                    b.Navigation("Clube");
                });

            modelBuilder.Entity("Padelizou.Models.Torneio", b =>
                {
                    b.HasOne("Padelizou.Models.Clube", "Clube")
                        .WithMany("Torneios")
                        .HasForeignKey("ClubeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clube");
                });

            modelBuilder.Entity("Padelizou.Models.TorneioOrganizador", b =>
                {
                    b.HasOne("Padelizou.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Torneio", "Torneio")
                        .WithMany()
                        .HasForeignKey("TorneioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");

                    b.Navigation("Torneio");
                });

            modelBuilder.Entity("padelizou.Models.Aula", b =>
                {
                    b.HasOne("Padelizou.Models.Jogador", "Aluno")
                        .WithMany("AulasRecebidas")
                        .HasForeignKey("AlunoId")
                        .HasConstraintName("FK__Aula__AlunoId__114A936A");

                    b.HasOne("Padelizou.Models.LocalAula", "LocalAula")
                        .WithMany()
                        .HasForeignKey("LocalAulaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Professor")
                        .WithMany("AulasDadas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("LocalAula");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("padelizou.Models.GrupoPrivado", b =>
                {
                    b.HasOne("Padelizou.Models.Jogador", "Administrador")
                        .WithMany()
                        .HasForeignKey("AdministradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("padelizou.Models.CategoriaPadrao", "CategoriaPadrao")
                        .WithMany()
                        .HasForeignKey("CategoriaPadraoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Padelizou.Models.Clube", "Clube")
                        .WithMany()
                        .HasForeignKey("ClubeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Administrador");

                    b.Navigation("CategoriaPadrao");

                    b.Navigation("Clube");
                });

            modelBuilder.Entity("padelizou.Models.GrupoTorneio", b =>
                {
                    b.HasOne("Padelizou.Models.Categoria", "Categoria")
                        .WithMany("GruposTorneio")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("padelizou.Models.InscricaoJogoAula", b =>
                {
                    b.HasOne("Padelizou.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("padelizou.Models.JogoAula", "JogoAula")
                        .WithMany()
                        .HasForeignKey("JogoAulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");

                    b.Navigation("JogoAula");
                });

            modelBuilder.Entity("padelizou.Models.JogadorGrupo", b =>
                {
                    b.HasOne("padelizou.Models.GrupoPrivado", "GrupoPrivado")
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GrupoPrivado");

                    b.Navigation("Jogador");
                });

            modelBuilder.Entity("padelizou.Models.JogoAula", b =>
                {
                    b.HasOne("padelizou.Models.CategoriaPadrao", "CategoriaPadrao")
                        .WithMany()
                        .HasForeignKey("CategoriaPadraoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.LocalAula", "LocalAula")
                        .WithMany()
                        .HasForeignKey("LocalAulaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Padelizou.Models.Jogador", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaPadrao");

                    b.Navigation("LocalAula");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Padelizou.Models.AvisoParceiro", b =>
                {
                    b.Navigation("Candidaturas");
                });

            modelBuilder.Entity("Padelizou.Models.Categoria", b =>
                {
                    b.Navigation("Duplas");

                    b.Navigation("GruposTorneio");

                    b.Navigation("Partidas");
                });

            modelBuilder.Entity("Padelizou.Models.Clube", b =>
                {
                    b.Navigation("Times");

                    b.Navigation("Torneios");
                });

            modelBuilder.Entity("Padelizou.Models.Dupla", b =>
                {
                    b.Navigation("PartidasDupla1");

                    b.Navigation("PartidasDupla2");
                });

            modelBuilder.Entity("Padelizou.Models.Jogador", b =>
                {
                    b.Navigation("AulasDadas");

                    b.Navigation("AulasRecebidas");

                    b.Navigation("DuplaJogador1s");

                    b.Navigation("DuplaJogador2s");

                    b.Navigation("JogadorCategorias");

                    b.Navigation("JogadorCidades");

                    b.Navigation("JogadorClubes");

                    b.Navigation("JogadorDiasHorarios");
                });

            modelBuilder.Entity("Padelizou.Models.LocalAula", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("Padelizou.Models.SessaoGrupo", b =>
                {
                    b.Navigation("Confirmacoes");
                });

            modelBuilder.Entity("Padelizou.Models.Time", b =>
                {
                    b.Navigation("Jogadores");
                });

            modelBuilder.Entity("Padelizou.Models.Torneio", b =>
                {
                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("padelizou.Models.GrupoTorneio", b =>
                {
                    b.Navigation("Duplas");
                });
#pragma warning restore 612, 618
        }
    }
}
