// Textos dos menus e dos controles, em PT e EN (tests/i18n.test.ts exige as duas tabelas iguais).
import { registerStrings } from '../i18n';

registerStrings('ui', {
  pt: {
    'device.kb1': 'Teclado (setas)',
    'device.kb2': 'Teclado (WASD)',
    'device.gp': 'Controle {n} — {name}',
    'device.gpGeneric': 'Controle {n}',

    'common.back': 'Voltar',
    'common.on': 'Ligado',
    'common.off': 'Desligado',
    'common.laps': '{n} voltas',
    'loading': 'Carregando…',

    'title.subtitle': 'corrida arcade cooperativa',
    'title.press': 'PRESSIONE ENTER OU START',
    'title.foot': 'até 4 jogadores em tela dividida',

    'main.cup': 'Campeonato',
    'main.quick': 'Corrida rápida',
    'main.timetrial': 'Contra-relógio',
    'main.records': 'Recordes',
    'main.options': 'Opções',
    'main.controls': 'Controles',
    'main.credits': 'Créditos',
    'main.quit': 'Sair',
    'main.hint.cup': 'Quatro copas de três pistas, em equipe ou versus',
    'main.hint.quick': 'Uma pista, as voltas que você quiser',
    'main.hint.timetrial': 'Sozinho na pista, contra o relógio',
    'main.hint.records': 'Melhores voltas e corridas por pista',
    'main.hint.options': 'Idioma, som, vídeo e regras da corrida',
    'main.hint.controls': 'Teclas, botões e dispositivos conectados',
    'main.hint.credits': 'Quem fez isto',
    'main.hint.quit': 'Fechar o jogo',

    'lobby.title': 'Lobby',
    'lobby.join': 'Aperte Enter / F / A para entrar',
    'lobby.joinHint': 'Enter ou Espaço: teclado 1 · F: teclado 2 · A ou Start: controle',
    'lobby.name': 'Nome',
    'lobby.car': 'Carro',
    'lobby.team': 'Time',
    'lobby.teamN': 'Time {n}',
    'lobby.ready': 'PRONTO',
    'lobby.readyDone': 'PRONTO ✓',
    'lobby.laps': 'Voltas',
    'lobby.leaveHint': 'Esc / B sai do assento',
    'lobby.stat.topSpeed': 'Velocidade',
    'lobby.stat.accel': 'Aceleração',
    'lobby.stat.handling': 'Curvas',
    'lobby.stat.economy': 'Economia',
    'lobby.options': 'Opções da corrida (Jogador 1)',
    'lobby.mode': 'Modo',
    'lobby.coop': 'Cooperativo',
    'lobby.versus': 'Versus',
    'lobby.start': 'INICIAR',
    'lobby.startHint': 'Todos prontos! Enter ou Start para começar',
    'lobby.waitHint': 'Precisa do Jogador 1 e de todos os assentos prontos',
    'lobby.needP1': 'O Jogador 1 entra para configurar a corrida',

    'cups.title': 'Escolha a copa',
    'cups.locked': 'Conclua a {cup}',
    'cups.hint': 'Enter ou A escolhe · Esc ou B volta ao lobby',

    'tracks.title': 'Escolha a pista',
    'tracks.bestLap': 'Melhor volta',
    'tracks.hint': 'Enter ou A escolhe · Esc ou B volta ao lobby',

    'results.title': 'Resultado',
    'results.name': 'Piloto',
    'results.car': 'Carro',
    'results.time': 'Tempo',
    'results.bestLap': 'Melhor volta',
    'results.points': 'Pontos',
    'results.dnf': 'não terminou',
    'results.record': 'RECORDE',
    'results.team': '{team}: {points} pontos — equipe nº {rank} nesta corrida',
    'results.qualified': 'CLASSIFICADO',
    'results.eliminated': 'ELIMINADO',
    'results.standings': 'CLASSIFICAÇÃO',
    'results.retry': 'TENTAR DE NOVO',
    'results.menu': 'MENU',

    'standings.title': 'Classificação',
    'standings.drivers': 'Pilotos',
    'standings.teams': 'Equipes',
    'standings.points': 'Pts',
    'standings.wins': 'Vit.',
    'standings.race': 'C{n}',
    'standings.next': 'Próxima corrida: {n} de {m} — {track}',
    'standings.champion': 'CAMPEÃO DA COPA!',
    'standings.eliminated': 'ELIMINADO',
    'standings.nextBtn': 'PRÓXIMA CORRIDA',
    'standings.menu': 'MENU',

    'pause.title': 'Pausa',
    'pause.resume': 'Continuar',
    'pause.restart': 'Reiniciar corrida',
    'pause.options': 'Opções',
    'pause.quit': 'Sair para o menu',

    'options.title': 'Opções',
    'options.general': 'Geral',
    'options.race': 'Corrida',
    'options.language': 'Idioma',
    'options.master': 'Volume geral',
    'options.music': 'Volume da música',
    'options.sfx': 'Volume dos efeitos',
    'options.fullscreen': 'Tela cheia',
    'options.quality': 'Qualidade',
    'options.quality.low': 'Baixa',
    'options.quality.medium': 'Média',
    'options.quality.high': 'Alta',
    'options.minimap': 'Minimapa',
    'options.shake': 'Tremor de tela',
    'options.track': 'Música',
    'options.musicAuto': 'Automática',
    'options.difficulty': 'Dificuldade',
    'options.gear': 'Câmbio',
    'options.gear.auto': 'Automático',
    'options.gear.manual': 'Manual',
    'options.totalCars': 'Carros na pista',
    'options.quickLaps': 'Voltas da corrida rápida',
    'options.assist.sharedNitro': 'Cofre de nitro',
    'options.assist.tow': 'Empurrão',
    'options.assist.teamDraft': 'Vácuo de equipe',
    'options.assist.catchup': 'Elástico',

    'controls.title': 'Controles',
    'controls.action': 'Ação',
    'controls.gamepad': 'Controle',
    'controls.accel': 'Acelerar',
    'controls.brake': 'Frear',
    'controls.steer': 'Virar',
    'controls.nitro': 'Nitro',
    'controls.gearUp': 'Marcha acima',
    'controls.gearDown': 'Marcha abaixo',
    'controls.confirm': 'Confirmar',
    'controls.back': 'Voltar',
    'controls.pause': 'Pausar',
    'controls.key.space': 'Espaço',
    'controls.key.stick': 'Analógico / D-pad',
    'controls.detected': 'Dispositivos detectados',
    'controls.connected': 'conectado',
    'controls.disconnected': 'desconectado',
    'controls.free': 'livre',
    'controls.seat': 'assento {n}',
    'controls.gamepadHint': 'Aperte um botão no controle para ele aparecer aqui',

    'records.title': 'Recordes',
    'records.stats': '{run} corridas, {won} vitórias, {cups} copas concluídas',
    'records.empty': 'Nenhum recorde ainda — vá correr!',
    'records.lap': 'Melhor volta',
    'records.race': '{n} voltas',

    'credits.title': 'Créditos',
    'credits.by': 'Feito por Felipe Bonamigo com Claude',
    'credits.inspired': 'Inspirado nos clássicos de corrida de 16 bits',
    'credits.tech': 'TypeScript, Canvas 2D, Web Audio, Vite e Electron',
    'credits.assets': 'Sem um único arquivo de arte ou som: tudo é desenhado e tocado por código',
  },
  en: {
    'device.kb1': 'Keyboard (arrows)',
    'device.kb2': 'Keyboard (WASD)',
    'device.gp': 'Gamepad {n} — {name}',
    'device.gpGeneric': 'Gamepad {n}',

    'common.back': 'Back',
    'common.on': 'On',
    'common.off': 'Off',
    'common.laps': '{n} laps',
    'loading': 'Loading…',

    'title.subtitle': 'co-op arcade racing',
    'title.press': 'PRESS ENTER OR START',
    'title.foot': 'up to 4 players in split screen',

    'main.cup': 'Championship',
    'main.quick': 'Quick race',
    'main.timetrial': 'Time trial',
    'main.records': 'Records',
    'main.options': 'Options',
    'main.controls': 'Controls',
    'main.credits': 'Credits',
    'main.quit': 'Quit',
    'main.hint.cup': 'Four cups of three tracks, as a team or versus',
    'main.hint.quick': 'One track, as many laps as you like',
    'main.hint.timetrial': 'Alone on the track, against the clock',
    'main.hint.records': 'Best laps and races per track',
    'main.hint.options': 'Language, sound, video and race rules',
    'main.hint.controls': 'Keys, buttons and connected devices',
    'main.hint.credits': 'Who made this',
    'main.hint.quit': 'Close the game',

    'lobby.title': 'Lobby',
    'lobby.join': 'Press Enter / F / A to join',
    'lobby.joinHint': 'Enter or Space: keyboard 1 · F: keyboard 2 · A or Start: gamepad',
    'lobby.name': 'Name',
    'lobby.car': 'Car',
    'lobby.team': 'Team',
    'lobby.teamN': 'Team {n}',
    'lobby.ready': 'READY',
    'lobby.readyDone': 'READY ✓',
    'lobby.laps': 'Laps',
    'lobby.leaveHint': 'Esc / B leaves the seat',
    'lobby.stat.topSpeed': 'Top speed',
    'lobby.stat.accel': 'Acceleration',
    'lobby.stat.handling': 'Handling',
    'lobby.stat.economy': 'Economy',
    'lobby.options': 'Race options (Player 1)',
    'lobby.mode': 'Mode',
    'lobby.coop': 'Co-op',
    'lobby.versus': 'Versus',
    'lobby.start': 'START',
    'lobby.startHint': 'Everyone is ready! Enter or Start to begin',
    'lobby.waitHint': 'Needs Player 1 and every taken seat ready',
    'lobby.needP1': 'Player 1 joins to set up the race',

    'cups.title': 'Choose a cup',
    'cups.locked': 'Finish the {cup}',
    'cups.hint': 'Enter or A picks · Esc or B returns to the lobby',

    'tracks.title': 'Choose a track',
    'tracks.bestLap': 'Best lap',
    'tracks.hint': 'Enter or A picks · Esc or B returns to the lobby',

    'results.title': 'Results',
    'results.name': 'Driver',
    'results.car': 'Car',
    'results.time': 'Time',
    'results.bestLap': 'Best lap',
    'results.points': 'Points',
    'results.dnf': 'DNF',
    'results.record': 'RECORD',
    'results.team': '{team}: {points} points — team #{rank} in this race',
    'results.qualified': 'QUALIFIED',
    'results.eliminated': 'ELIMINATED',
    'results.standings': 'STANDINGS',
    'results.retry': 'TRY AGAIN',
    'results.menu': 'MENU',

    'standings.title': 'Standings',
    'standings.drivers': 'Drivers',
    'standings.teams': 'Teams',
    'standings.points': 'Pts',
    'standings.wins': 'Wins',
    'standings.race': 'R{n}',
    'standings.next': 'Next race: {n} of {m} — {track}',
    'standings.champion': 'CUP CHAMPION!',
    'standings.eliminated': 'ELIMINATED',
    'standings.nextBtn': 'NEXT RACE',
    'standings.menu': 'MENU',

    'pause.title': 'Paused',
    'pause.resume': 'Resume',
    'pause.restart': 'Restart race',
    'pause.options': 'Options',
    'pause.quit': 'Quit to menu',

    'options.title': 'Options',
    'options.general': 'General',
    'options.race': 'Race',
    'options.language': 'Language',
    'options.master': 'Master volume',
    'options.music': 'Music volume',
    'options.sfx': 'Effects volume',
    'options.fullscreen': 'Fullscreen',
    'options.quality': 'Quality',
    'options.quality.low': 'Low',
    'options.quality.medium': 'Medium',
    'options.quality.high': 'High',
    'options.minimap': 'Minimap',
    'options.shake': 'Screen shake',
    'options.track': 'Music',
    'options.musicAuto': 'Automatic',
    'options.difficulty': 'Difficulty',
    'options.gear': 'Gearbox',
    'options.gear.auto': 'Automatic',
    'options.gear.manual': 'Manual',
    'options.totalCars': 'Cars on track',
    'options.quickLaps': 'Quick race laps',
    'options.assist.sharedNitro': 'Nitro vault',
    'options.assist.tow': 'Tow',
    'options.assist.teamDraft': 'Team draft',
    'options.assist.catchup': 'Rubber band',

    'controls.title': 'Controls',
    'controls.action': 'Action',
    'controls.gamepad': 'Gamepad',
    'controls.accel': 'Accelerate',
    'controls.brake': 'Brake',
    'controls.steer': 'Steer',
    'controls.nitro': 'Nitro',
    'controls.gearUp': 'Gear up',
    'controls.gearDown': 'Gear down',
    'controls.confirm': 'Confirm',
    'controls.back': 'Back',
    'controls.pause': 'Pause',
    'controls.key.space': 'Space',
    'controls.key.stick': 'Stick / D-pad',
    'controls.detected': 'Detected devices',
    'controls.connected': 'connected',
    'controls.disconnected': 'disconnected',
    'controls.free': 'free',
    'controls.seat': 'seat {n}',
    'controls.gamepadHint': 'Press a button on the gamepad so it shows up here',

    'records.title': 'Records',
    'records.stats': '{run} races, {won} wins, {cups} cups completed',
    'records.empty': 'No records yet — go race!',
    'records.lap': 'Best lap',
    'records.race': '{n} laps',

    'credits.title': 'Credits',
    'credits.by': 'Made by Felipe Bonamigo with Claude',
    'credits.inspired': 'Inspired by the 16-bit racing classics',
    'credits.tech': 'TypeScript, Canvas 2D, Web Audio, Vite and Electron',
    'credits.assets': 'Not a single art or sound file: everything is drawn and played by code',
  },
});
