// Textos do online (tela, lobby em rede, avisos na corrida) e a entrada "Online" do menu principal.
import { registerStrings } from '../i18n';

registerStrings('online', {
  pt: {
    'title': 'Online',
    'intro': 'Corra com amigos pela internet. Um computador cria a sala e passa o código de 5 letras; cada computador pode ter 1 ou 2 jogadores (até 4 no total).',
    'connect.server': 'Servidor',
    'connect.create': 'Criar sala',
    'connect.createHint': 'Você vira o anfitrião: escolhe a pista, as voltas e larga.',
    'connect.joinHint': 'Digite o código de 5 letras que o anfitrião passou.',
    'connect.code': 'Código da sala',
    'connect.join': 'Entrar na sala',
    'connect.connecting': 'Conectando a {url}…',
    'connect.cancel': 'Cancelar',
    'connect.serverSaved': 'Servidor salvo',
    'connect.typeHint': 'Enter no campo confirma · Esc sai do campo',

    'lobby.room': 'Sala',
    'lobby.codeHint': 'Passe este código para quem vai entrar',
    'lobby.players': 'Jogadores',
    'lobby.count': '{n}/4',
    'lobby.you': 'você',
    'lobby.host': 'anfitrião',
    'lobby.ready': 'pronto',
    'lobby.notReady': 'escolhendo',
    'lobby.offline': 'desconectado',
    'lobby.here': 'Neste computador',
    'lobby.addLocal': 'Segundo jogador aqui? Aperte F (teclado WASD) ou A num controle.',
    'lobby.removeLocal': 'Tirar o jogador 2',
    'lobby.name': 'Nome',
    'lobby.car': 'Carro',
    'lobby.readyBtn': 'PRONTO',
    'lobby.start': 'LARGAR',
    'lobby.race': 'Corrida',
    'lobby.track': 'Pista',
    'lobby.laps': 'Voltas',
    'lobby.mode': 'Modo',
    'lobby.coop': 'Cooperativo',
    'lobby.versus': 'Versus',
    'lobby.difficulty': 'Dificuldade',
    'lobby.cars': 'Carros na pista',
    'lobby.delay': 'Atraso',
    'lobby.delayValue': '{n} ticks · {ms} ms',
    'lobby.leave': 'Sair da sala',
    'lobby.waitHost': 'O anfitrião escolhe a pista e larga',
    'lobby.needPeer': 'Esperando outro computador entrar',
    'lobby.waitPeers': 'Esperando todos conectarem',
    'lobby.waitReady': 'Esperando todos ficarem prontos',
    'lobby.canStart': 'Todos prontos! LARGAR começa a corrida',
    'lobby.guestReady': 'Pronto! Esperando o anfitrião largar',
    'lobby.guestHint': 'Escolha nome e carro e aperte PRONTO',
    'lobby.lapsValue': '{n} voltas',
    'lobby.oneLap': '1 volta',

    'quit.title': 'Sair da partida?',
    'quit.body': 'A corrida online não pausa: ela continua enquanto este aviso está aberto. Se você sair, a IA assume o seu carro.',
    'quit.stay': 'Continuar correndo',
    'quit.leave': 'Sair da partida',

    'results.title': 'Resultado',
    'results.backToRoom': 'Voltar à sala',
    'results.leave': 'Sair da sala',
    'results.ai': 'IA',

    'hud.ping': 'ping {ms} ms',
    'hud.pingUnknown': 'ping —',
    'hud.delay': 'atraso {n} ({ms} ms)',
    'hud.waiting': 'Aguardando {name}…',
    'hud.waitingLost': 'Aguardando {name} reconectar…',
    'hud.reconnecting': 'Conexão perdida — tentando voltar ({s} s)',
    'hud.syncing': 'Reconectado — recebendo a corrida…',
    'hud.desync': 'Dessincronia no tick {tick}: os computadores podem estar vendo corridas diferentes',

    'err.title': 'Sem conexão',
    'err.back': 'Voltar',
    'err.menu': 'Menu principal',
    'err.connect': 'Não foi possível conectar ao servidor. Confira o endereço e se o relay está rodando (npm run relay).',
    'err.lost': 'A conexão com o servidor caiu.',
    'err.no_room': 'Sala não encontrada. Confira o código.',
    'err.full': 'Sala cheia: até 4 jogadores no total.',
    'err.started': 'A corrida desta sala já começou.',
    'err.version': 'O servidor usa outra versão do jogo.',
    'err.expired': 'Não deu para voltar à partida a tempo.',
    'err.rooms': 'O servidor está lotado. Tente de novo mais tarde.',
    'err.badCode': 'Código inválido: são 5 letras (sem I nem O).',
    'err.noSeat': 'Este computador ficou sem lugar na corrida.',
    'err.snapshot': 'O estado da corrida recebido do anfitrião veio inválido.',
    'err.syncTimeout': 'Voltou à sala, mas o anfitrião não mandou o estado da corrida a tempo.',
    'err.badUrl': 'Endereço inválido. Exemplo: ws://192.168.0.10:8787',
    'err.unavailable': 'O online não está disponível aqui.',
  },
  en: {
    'title': 'Online',
    'intro': 'Race with friends over the internet. One computer creates the room and shares the 5-letter code; each computer can have 1 or 2 players (up to 4 in total).',
    'connect.server': 'Server',
    'connect.create': 'Create room',
    'connect.createHint': 'You become the host: pick the track and laps, then start.',
    'connect.joinHint': 'Type the 5-letter code the host shared.',
    'connect.code': 'Room code',
    'connect.join': 'Join room',
    'connect.connecting': 'Connecting to {url}…',
    'connect.cancel': 'Cancel',
    'connect.serverSaved': 'Server saved',
    'connect.typeHint': 'Enter in a field confirms · Esc leaves the field',

    'lobby.room': 'Room',
    'lobby.codeHint': 'Share this code with whoever is joining',
    'lobby.players': 'Players',
    'lobby.count': '{n}/4',
    'lobby.you': 'you',
    'lobby.host': 'host',
    'lobby.ready': 'ready',
    'lobby.notReady': 'choosing',
    'lobby.offline': 'disconnected',
    'lobby.here': 'On this computer',
    'lobby.addLocal': 'Second player here? Press F (WASD keyboard) or A on a controller.',
    'lobby.removeLocal': 'Remove player 2',
    'lobby.name': 'Name',
    'lobby.car': 'Car',
    'lobby.readyBtn': 'READY',
    'lobby.start': 'START',
    'lobby.race': 'Race',
    'lobby.track': 'Track',
    'lobby.laps': 'Laps',
    'lobby.mode': 'Mode',
    'lobby.coop': 'Co-op',
    'lobby.versus': 'Versus',
    'lobby.difficulty': 'Difficulty',
    'lobby.cars': 'Cars on track',
    'lobby.delay': 'Delay',
    'lobby.delayValue': '{n} ticks · {ms} ms',
    'lobby.leave': 'Leave room',
    'lobby.waitHost': 'The host picks the track and starts',
    'lobby.needPeer': 'Waiting for another computer to join',
    'lobby.waitPeers': 'Waiting for everyone to connect',
    'lobby.waitReady': 'Waiting for everyone to be ready',
    'lobby.canStart': 'Everyone is ready! START begins the race',
    'lobby.guestReady': 'Ready! Waiting for the host to start',
    'lobby.guestHint': 'Pick a name and a car, then press READY',
    'lobby.lapsValue': '{n} laps',
    'lobby.oneLap': '1 lap',

    'quit.title': 'Leave the match?',
    'quit.body': 'Online races do not pause: the race goes on while this is open. If you leave, the AI takes over your car.',
    'quit.stay': 'Keep racing',
    'quit.leave': 'Leave match',

    'results.title': 'Results',
    'results.backToRoom': 'Back to room',
    'results.leave': 'Leave room',
    'results.ai': 'AI',

    'hud.ping': 'ping {ms} ms',
    'hud.pingUnknown': 'ping —',
    'hud.delay': 'delay {n} ({ms} ms)',
    'hud.waiting': 'Waiting for {name}…',
    'hud.waitingLost': 'Waiting for {name} to reconnect…',
    'hud.reconnecting': 'Connection lost — trying to get back ({s} s)',
    'hud.syncing': 'Reconnected — receiving the race…',
    'hud.desync': 'Desync at tick {tick}: the computers may be seeing different races',

    'err.title': 'No connection',
    'err.back': 'Back',
    'err.menu': 'Main menu',
    'err.connect': 'Could not connect to the server. Check the address and that the relay is running (npm run relay).',
    'err.lost': 'The connection to the server dropped.',
    'err.no_room': 'Room not found. Check the code.',
    'err.full': 'Room is full: up to 4 players in total.',
    'err.started': 'This room is already racing.',
    'err.version': 'The server runs a different version of the game.',
    'err.expired': 'Could not get back into the match in time.',
    'err.rooms': 'The server is full. Try again later.',
    'err.badCode': 'Invalid code: 5 letters (no I or O).',
    'err.noSeat': 'This computer was left without a seat in the race.',
    'err.snapshot': 'The race state received from the host was invalid.',
    'err.syncTimeout': 'Got back into the room, but the host did not send the race state in time.',
    'err.badUrl': 'Invalid address. Example: ws://192.168.0.10:8787',
    'err.unavailable': 'Online is not available here.',
  },
});

registerStrings('ui', {
  pt: { 'main.online': 'Online', 'main.hint.online': 'Corra com amigos pela internet, até 4 jogadores' },
  en: { 'main.online': 'Online', 'main.hint.online': 'Race with friends over the internet, up to 4 players' },
});
