// Textos dos rivais (src/game/rivals.ts): personalidades, rótulos e as falas. Cada rival de copa
// (CUP_RIVALS em data/drivers.ts) tem apresentação e três falas próprias; um piloto sem falas próprias
// (copa nova) usa as da personalidade dele.
import { registerStrings } from '../i18n';

registerStrings('rivals', {
  pt: {
    'label': 'Rival',
    'cupRival': 'Rival da copa',
    'result': 'Rival: {name} — {pos}',
    'standing': 'Rival: {name} — {pos} na copa',
    'ordinal': '{n}º',
    'garage': 'Rival: {name} ({personality})',
    'hudTag': 'RIVAL',
    'personality.clean': 'Limpo',
    'personality.aggressive': 'Agressivo',
    'personality.blocker': 'Bloqueador',
    'personality.erratic': 'Errático',

    'line.ze_turbo.intro': 'Aqui é o meu quintal. Quem quiser passar vai ter que me tirar da frente.',
    'line.ze_turbo.taunt': 'Viu minha traseira de perto? Aproveita, é a vista que você vai ter a copa inteira.',
    'line.ze_turbo.respect': 'Tá bom, tá bom… essa foi sua. Mas não se acostuma.',
    'line.ze_turbo.revenge': 'Achou que ia ficar por isso mesmo? O troco veio com juros.',
    'line.tom_blake.intro': 'Estrada larga, porta estreita. A porta sou eu.',
    'line.tom_blake.taunt': 'Procurando uma brecha? Continue procurando.',
    'line.tom_blake.respect': 'Você achou o espaço que eu não deixei. Respeito.',
    'line.tom_blake.revenge': 'Da última vez você passou. Hoje a porta ficou fechada.',
    'line.kenji_sato.intro': 'Traçado limpo, sem toque. Que vença quem errar menos.',
    'line.kenji_sato.taunt': 'Cada curva tem um traçado certo. Hoje ele era meu.',
    'line.kenji_sato.respect': 'Corrida limpa e rápida. Foi uma honra ficar atrás de você.',
    'line.kenji_sato.revenge': 'Estudei seus pontos de frenagem. Obrigado pela aula da última corrida.',
    'line.hugo_klein.intro': 'Na Europa se corre com precisão. E eu ocupo a pista inteira com precisão.',
    'line.hugo_klein.taunt': 'Ultrapassagem não se pede, se conquista. Você não conquistou.',
    'line.hugo_klein.respect': 'Uma ultrapassagem digna de manual. Anotado.',
    'line.hugo_klein.revenge': 'Ordem restabelecida: eu na frente, você atrás.',
    'line.bianca_rey.intro': 'Às vezes eu erro a curva. Às vezes erro e ainda chego na sua frente.',
    'line.bianca_rey.taunt': 'Passei pela grama, pela terra e por você. Nessa ordem.',
    'line.bianca_rey.respect': 'Tá, hoje passei mais tempo no mato que na pista. Mérito seu mesmo assim.',
    'line.bianca_rey.revenge': 'Caótica, sim. Lenta, nunca. Voltei!',
    'line.sasha_kova.intro': 'No outback não tem freio. Tem coragem.',
    'line.sasha_kova.taunt': 'Freei depois de você em todas as curvas. Deu para sentir?',
    'line.sasha_kova.respect': 'Você não piscou. Gosto disso.',
    'line.sasha_kova.revenge': 'Da última vez você me pegou. Hoje eu mordi primeiro.',
    'line.iris_lund.intro': 'O gelo não perdoa erro. E eu não cometo.',
    'line.iris_lund.taunt': 'Calma, precisão, primeiro lugar. Tente de novo.',
    'line.iris_lund.respect': 'Frio como a pista. Belo trabalho.',
    'line.iris_lund.revenge': 'O gelo derreteu? Não. Só acertei as contas com você.',
    'line.marco_rossi.intro': 'Última copa, último obstáculo: eu. Andiamo.',
    'line.marco_rossi.taunt': 'Bela corrida… para mim.',
    'line.marco_rossi.respect': 'Bravo. Você mereceu cada metro.',
    'line.marco_rossi.revenge': 'Ninguém me passa duas vezes seguidas. Ninguém.',
    'line.caio_brasa.intro': 'No Sul a serra é minha. Cada curva dessas eu já fiz de olho fechado.',
    'line.caio_brasa.taunt': 'Pega a cuia e senta: a corrida acabou e eu cheguei primeiro.',
    'line.caio_brasa.respect': 'Bah, que pilotagem! Hoje foi tua, tchê.',
    'line.caio_brasa.revenge': 'Achou que o frio da serra ia me parar? Voltei quente.',
    'line.duda_ferraz.intro': 'No cerrado a estrada é larga. Eu ocupo ela toda.',
    'line.duda_ferraz.taunt': 'Ficou procurando a brecha de novo? No Planalto ela não existe.',
    'line.duda_ferraz.respect': 'Passou por onde eu não deixava. Merecido.',
    'line.duda_ferraz.revenge': 'Da última vez você achou a porta. Hoje ela estava trancada.',
    'line.nina_costa.intro': 'Nove estados de litoral e eu conheço cada metro da orla. Vem.',
    'line.nina_costa.taunt': 'Traçado limpo, vento a favor, primeiro lugar. Simples assim.',
    'line.nina_costa.respect': 'Que corrida bonita. Seu carimbo foi merecido.',
    'line.nina_costa.revenge': 'Aprendi com a última. A orla hoje foi minha.',
    'line.dani_souza.intro': 'Na Amazônia ninguém sabe o que vem depois da curva. Nem eu.',
    'line.dani_souza.taunt': 'Fui pela margem, pela lama e por você. Cheguei na frente.',
    'line.dani_souza.respect': 'Hoje o rio me levou para o mato mais que para a pista. Parabéns.',
    'line.dani_souza.revenge': 'Achou que a floresta tinha me engolido? Voltei!',

    'generic.clean.intro': 'Corrida limpa, sem toques. Vamos ver quem é mais rápido.',
    'generic.clean.taunt': 'Traçado perfeito, resultado perfeito.',
    'generic.clean.respect': 'Rápido e limpo. Bela corrida.',
    'generic.clean.revenge': 'Aprendi com a última. Hoje foi minha.',
    'generic.aggressive.intro': 'Sai da frente ou sai da pista.',
    'generic.aggressive.taunt': 'Eu avisei: freio é para quem tem medo.',
    'generic.aggressive.respect': 'Hoje você foi mais corajoso que eu.',
    'generic.aggressive.revenge': 'Fiquei devendo uma. Paguei.',
    'generic.blocker.intro': 'Pode tentar me passar. Todo mundo tenta.',
    'generic.blocker.taunt': 'Porta fechada de novo.',
    'generic.blocker.respect': 'Você achou a brecha. Bem jogado.',
    'generic.blocker.revenge': 'Da última vez você passou. Hoje, não.',
    'generic.erratic.intro': 'Nem eu sei o que vou fazer na próxima curva. Nem você.',
    'generic.erratic.taunt': 'Grama, zebra, tanto faz: cheguei na frente.',
    'generic.erratic.respect': 'Errei demais hoje. Parabéns.',
    'generic.erratic.revenge': 'Caos organizado. Voltei.',
  },
  en: {
    'label': 'Rival',
    'cupRival': 'Cup rival',
    'result': 'Rival: {name} — {pos}',
    'standing': 'Rival: {name} — {pos} in the cup',
    'ordinal': '{n}{s}',
    'garage': 'Rival: {name} ({personality})',
    'hudTag': 'RIVAL',
    'personality.clean': 'Clean',
    'personality.aggressive': 'Aggressive',
    'personality.blocker': 'Blocker',
    'personality.erratic': 'Erratic',

    'line.ze_turbo.intro': 'This is my backyard. If you want past, you will have to move me.',
    'line.ze_turbo.taunt': 'Enjoyed the view of my rear bumper? Get used to it — all cup long.',
    'line.ze_turbo.respect': 'Fine, fine… that one was yours. Don\'t get used to it.',
    'line.ze_turbo.revenge': 'Thought I\'d let that slide? Payback, with interest.',
    'line.tom_blake.intro': 'Wide road, narrow door. I\'m the door.',
    'line.tom_blake.taunt': 'Looking for a gap? Keep looking.',
    'line.tom_blake.respect': 'You found the space I didn\'t leave. Respect.',
    'line.tom_blake.revenge': 'Last time you got through. Today the door stayed shut.',
    'line.kenji_sato.intro': 'Clean lines, no contact. May the one with fewer mistakes win.',
    'line.kenji_sato.taunt': 'Every corner has a right line. Today it was mine.',
    'line.kenji_sato.respect': 'Clean and fast. It was an honor to follow you.',
    'line.kenji_sato.revenge': 'I studied your braking points. Thanks for last race\'s lesson.',
    'line.hugo_klein.intro': 'In Europe we race with precision. I take up the whole road — precisely.',
    'line.hugo_klein.taunt': 'A pass is not requested, it is earned. You did not earn it.',
    'line.hugo_klein.respect': 'A textbook pass. Noted.',
    'line.hugo_klein.revenge': 'Order restored: me ahead, you behind.',
    'line.bianca_rey.intro': 'Sometimes I miss a corner. Sometimes I miss it and still beat you.',
    'line.bianca_rey.taunt': 'Through the grass, through the dirt, and past you. In that order.',
    'line.bianca_rey.respect': 'Okay, I spent more time in the bushes than on track. Still, well earned.',
    'line.bianca_rey.revenge': 'Chaotic, yes. Slow, never. I\'m back!',
    'line.sasha_kova.intro': 'In the outback there are no brakes. Just nerve.',
    'line.sasha_kova.taunt': 'I braked later than you in every corner. Did you feel it?',
    'line.sasha_kova.respect': 'You didn\'t blink. I like that.',
    'line.sasha_kova.revenge': 'Last time you got me. Today I bit first.',
    'line.iris_lund.intro': 'Ice forgives no mistakes. And I make none.',
    'line.iris_lund.taunt': 'Calm, precise, ahead. Try again.',
    'line.iris_lund.respect': 'Cool as the track. Nice work.',
    'line.iris_lund.revenge': 'Did the ice melt? No. I just settled the score.',
    'line.marco_rossi.intro': 'Last cup, last obstacle: me. Andiamo.',
    'line.marco_rossi.taunt': 'Bella race… for me.',
    'line.marco_rossi.respect': 'Bravo. You earned every meter.',
    'line.marco_rossi.revenge': 'Nobody passes me twice in a row. Nobody.',
    'line.caio_brasa.intro': 'Down South the mountains are mine. I could drive these bends blindfolded.',
    'line.caio_brasa.taunt': 'Grab some mate and sit down: the race is over and I got there first.',
    'line.caio_brasa.respect': 'Bah, what a drive! Today was yours, tchê.',
    'line.caio_brasa.revenge': 'Thought the mountain cold would stop me? I came back hot.',
    'line.duda_ferraz.intro': 'Out on the plateau the road is wide. I take up all of it.',
    'line.duda_ferraz.taunt': 'Still looking for a gap? Up here there is none.',
    'line.duda_ferraz.respect': 'You went through where I left no room. Well earned.',
    'line.duda_ferraz.revenge': 'Last time you found the door. Today it was locked.',
    'line.nina_costa.intro': 'Nine coastal states and I know every meter of the shore. Come on.',
    'line.nina_costa.taunt': 'Clean line, tailwind, first place. Simple as that.',
    'line.nina_costa.respect': 'What a beautiful race. You earned that stamp.',
    'line.nina_costa.revenge': 'I learned from last time. The shore was mine today.',
    'line.dani_souza.intro': 'In the Amazon nobody knows what comes after the bend. Not even me.',
    'line.dani_souza.taunt': 'Through the riverbank, the mud and you. I got there first.',
    'line.dani_souza.respect': 'The river took me into the bush more than down the road today. Congrats.',
    'line.dani_souza.revenge': 'Thought the jungle swallowed me? I am back!',

    'generic.clean.intro': 'Clean racing, no contact. Let\'s see who is faster.',
    'generic.clean.taunt': 'Perfect line, perfect result.',
    'generic.clean.respect': 'Fast and clean. Great race.',
    'generic.clean.revenge': 'I learned from the last one. Today was mine.',
    'generic.aggressive.intro': 'Get out of the way or get off the road.',
    'generic.aggressive.taunt': 'Told you: brakes are for the scared.',
    'generic.aggressive.respect': 'Today you were braver than me.',
    'generic.aggressive.revenge': 'I owed you one. Paid.',
    'generic.blocker.intro': 'Go ahead, try to pass me. Everybody tries.',
    'generic.blocker.taunt': 'Door closed again.',
    'generic.blocker.respect': 'You found the gap. Well played.',
    'generic.blocker.revenge': 'Last time you got through. Not today.',
    'generic.erratic.intro': 'Not even I know what I\'ll do in the next corner. Neither do you.',
    'generic.erratic.taunt': 'Grass, kerb, whatever: I finished ahead.',
    'generic.erratic.respect': 'Too many mistakes today. Congratulations.',
    'generic.erratic.revenge': 'Organized chaos. I\'m back.',
  },
});
