// Textos dos modos de festa (torneio de sofá, escolta, revezamento), em PT e EN. Estende também 'ui'
// (item "Festa" do menu principal e o nome de cada modo no chip do lobby: `ui.main.<modo>`).
import { registerStrings } from '../i18n';

registerStrings('ui', {
  pt: {
    'main.party': 'Festa',
    'main.hint.party': 'Torneio de sofá, escolta e revezamento — só no mesmo computador',
    'main.tournament': 'Torneio de sofá',
    'main.escort': 'Escolta',
    'main.relay': 'Revezamento',
  },
  en: {
    'main.party': 'Party',
    'main.hint.party': 'Couch tournament, escort and relay — same computer only',
    'main.tournament': 'Couch tournament',
    'main.escort': 'Escort',
    'main.relay': 'Relay',
  },
});

registerStrings('party', {
  pt: {
    'title': 'Festa',
    'localOnly': 'Só local: estes modos são para o mesmo computador e não existem no online.',
    'onlineRefused': 'Os modos de festa são só locais; o online corre só a corrida rápida.',
    'mode.tournament.desc': '2 a 8 pessoas revezando até 4 controles. Baterias contra a IA, pontos acumulados e final com os 4 melhores.',
    'mode.escort.desc': 'A equipe protege um VIP mais lento. Empurre-o por trás e segure os rivais: ele precisa chegar entre os 3 primeiros.',
    'mode.relay.desc': 'Um carro por dupla. A cada volta o controle passa ao parceiro — mas a troca só acontece no box.',
    'mode.tournament.who': '2–8 pessoas · 1–4 controles',
    'mode.escort.who': '1–4 jogadores em equipe',
    'mode.relay.who': '2 ou 4 jogadores, em duplas',

    'lobby.tournamentNote': 'Este controle vai passar de mão em mão. Nomes e carros vêm na inscrição.',
    'lobby.relayPairs': 'O revezamento precisa de 2 ou 4 jogadores: P1 + P2 e P3 + P4 dividem um carro.',
    'lobby.pairN': 'Dupla {n}',
    'lobby.partnerCar': 'A dupla corre no carro de {name}. Você assume no box, a cada volta.',
    'lobby.escortTeam': 'Escolta do VIP',
    'lobby.controllers': 'Controles do torneio',

    't.title': 'Inscrição do torneio',
    't.players': 'Pilotos ({n} de {max})',
    't.add': 'Adicionar piloto',
    't.remove': 'Remover o último',
    't.defaultName': 'Piloto {n}',
    't.rounds': 'Rodadas classificatórias',
    't.cup': 'Pistas',
    't.laps': 'Voltas por bateria',
    't.controllers.one': '1 controle ligado',
    't.controllers.other': '{n} controles ligados',
    't.summary': '{heats} por rodada · {final}',
    't.heats.one': '1 bateria',
    't.heats.other': '{n} baterias',
    't.final': 'final com os {n} melhores',
    't.noFinal': 'sem final (só 1 controle)',
    't.tracksLine': 'Rodadas: {tracks} · Final: {final}',
    't.nameHint': 'Enter edita o nome · ← → troca o carro',
    't.start': 'COMEÇAR TORNEIO',
    't.err.fewPlayers': 'Inscreva pelo menos 2 pilotos.',
    't.err.manyPlayers': 'No máximo 8 pilotos.',
    't.err.controllers': 'Ligue de 1 a 4 controles no lobby.',
    't.err.rounds': 'Escolha de 1 a 3 rodadas.',
    't.err.tracks': 'Esta copa não tem pistas suficientes.',
    't.err.emptyName': 'Todo piloto precisa de um nome.',
    't.err.sameName': 'Dois pilotos com o mesmo nome.',
    't.round': 'Rodada {r} de {total}',
    't.heat': 'Bateria {n} de {m}',
    't.final.title': 'FINAL',

    'handoff.title': 'Passe o controle',
    'handoff.pass': 'Passe o controle {n} para {name}',
    'handoff.keep': '{name} fica com o controle {n}',
    'handoff.go': 'LARGAR',
    'handoff.hint': 'Todos com o controle na mão? Confirme para largar.',
    'handoff.table': 'Classificação',
    'handoff.quit': 'Abandonar torneio',
    'handoff.grid': 'Larga na frente quem está mais bem classificado.',

    'table.title': 'Torneio',
    'table.name': 'Piloto',
    'table.points': 'Pts',
    'table.heats': 'Baterias',
    'table.best': 'Melhor',
    'table.time': 'Tempo',
    'table.final': 'Final',
    'table.tiebreak': 'Desempate: pontos → melhor colocação → menor tempo somado → ordem de inscrição.',
    'table.finalists': 'Vão à final os {n} primeiros.',
    'table.champion': 'Campeão do torneio: {name}!',
    'table.chip.one': '{n} pilotos · 1 bateria',
    'table.chip.other': '{n} pilotos · {heats} baterias',
    'table.after': 'Depois de {n} de {m} baterias classificatórias',
    'table.next': 'PRÓXIMA BATERIA',
    'table.toFinal': 'PARA A FINAL',
    'table.menu': 'MENU',
    'table.finalist': 'FINAL',

    'results.continue': 'CONTINUAR',

    'escort.hud': 'VIP em {pos} · meta: top 3',
    'escort.pushing': 'Empurrando o VIP!',
    'escort.won': 'Missão cumprida: o VIP chegou em {pos}!',
    'escort.lost': 'O VIP chegou em {pos} — ele precisava do pódio.',

    'relay.waiting': 'Sua vez na próxima troca',
    'relay.pitNow': 'Box! Passe o controle para {name}',
    'relay.yourTurn': 'SUA VEZ!',
    'relay.handed': 'Controle com {name}',
    'relay.missed': 'Passou do box: {name} segue mais uma volta',
    'relay.swaps.one': '{name}: 1 troca',
    'relay.swaps.other': '{name}: {n} trocas',
  },
  en: {
    'title': 'Party',
    'localOnly': 'Local only: these modes are for one computer and are not available online.',
    'onlineRefused': 'Party modes are local only; online plays quick races only.',
    'mode.tournament.desc': '2 to 8 people sharing up to 4 controllers. Heats against the AI, points add up, and a final for the top 4.',
    'mode.escort.desc': 'The team protects a slower VIP. Push it from behind and hold the rivals back: it must finish in the top 3.',
    'mode.relay.desc': 'One car per pair. Every lap control passes to your partner — but the swap only happens in the pit.',
    'mode.tournament.who': '2–8 people · 1–4 controllers',
    'mode.escort.who': '1–4 players as a team',
    'mode.relay.who': '2 or 4 players, in pairs',

    'lobby.tournamentNote': 'This controller will be passed around. Names and cars come in the sign-up.',
    'lobby.relayPairs': 'Relay needs 2 or 4 players: P1 + P2 and P3 + P4 share a car.',
    'lobby.pairN': 'Pair {n}',
    'lobby.partnerCar': 'The pair races in {name}\'s car. You take over in the pit, every lap.',
    'lobby.escortTeam': 'VIP escort',
    'lobby.controllers': 'Tournament controllers',

    't.title': 'Tournament sign-up',
    't.players': 'Drivers ({n} of {max})',
    't.add': 'Add driver',
    't.remove': 'Remove the last one',
    't.defaultName': 'Driver {n}',
    't.rounds': 'Qualifying rounds',
    't.cup': 'Tracks',
    't.laps': 'Laps per heat',
    't.controllers.one': '1 controller connected',
    't.controllers.other': '{n} controllers connected',
    't.summary': '{heats} per round · {final}',
    't.heats.one': '1 heat',
    't.heats.other': '{n} heats',
    't.final': 'final for the top {n}',
    't.noFinal': 'no final (only 1 controller)',
    't.tracksLine': 'Rounds: {tracks} · Final: {final}',
    't.nameHint': 'Enter edits the name · ← → changes the car',
    't.start': 'START TOURNAMENT',
    't.err.fewPlayers': 'Sign up at least 2 drivers.',
    't.err.manyPlayers': 'At most 8 drivers.',
    't.err.controllers': 'Connect 1 to 4 controllers in the lobby.',
    't.err.rounds': 'Choose 1 to 3 rounds.',
    't.err.tracks': 'This cup does not have enough tracks.',
    't.err.emptyName': 'Every driver needs a name.',
    't.err.sameName': 'Two drivers with the same name.',
    't.round': 'Round {r} of {total}',
    't.heat': 'Heat {n} of {m}',
    't.final.title': 'FINAL',

    'handoff.title': 'Pass the controller',
    'handoff.pass': 'Pass controller {n} to {name}',
    'handoff.keep': '{name} keeps controller {n}',
    'handoff.go': 'GO',
    'handoff.hint': 'Everyone holding a controller? Confirm to start.',
    'handoff.table': 'Standings',
    'handoff.quit': 'Quit tournament',
    'handoff.grid': 'The best ranked driver starts in front.',

    'table.title': 'Tournament',
    'table.name': 'Driver',
    'table.points': 'Pts',
    'table.heats': 'Heats',
    'table.best': 'Best',
    'table.time': 'Time',
    'table.final': 'Final',
    'table.tiebreak': 'Tiebreak: points → best finish → lowest total time → sign-up order.',
    'table.finalists': 'The top {n} go to the final.',
    'table.champion': 'Tournament champion: {name}!',
    'table.chip.one': '{n} drivers · 1 heat',
    'table.chip.other': '{n} drivers · {heats} heats',
    'table.after': 'After {n} of {m} qualifying heats',
    'table.next': 'NEXT HEAT',
    'table.toFinal': 'TO THE FINAL',
    'table.menu': 'MENU',
    'table.finalist': 'FINAL',

    'results.continue': 'CONTINUE',

    'escort.hud': 'VIP in {pos} · goal: top 3',
    'escort.pushing': 'Pushing the VIP!',
    'escort.won': 'Mission accomplished: the VIP finished {pos}!',
    'escort.lost': 'The VIP finished {pos} — it needed the podium.',

    'relay.waiting': 'Your turn at the next swap',
    'relay.pitNow': 'Pit! Hand control to {name}',
    'relay.yourTurn': 'YOUR TURN!',
    'relay.handed': '{name} has control',
    'relay.missed': 'Missed the pit: {name} drives another lap',
    'relay.swaps.one': '{name}: 1 swap',
    'relay.swaps.other': '{name}: {n} swaps',
  },
});
