// Textos do passaporte da Expedição Brasil (src/ui/screens/passport.ts): a tela, o cartão-postal de cada estado e
// os nomes dos marcos (ids de src/core/data/places.ts). Vocabulário da Expedição (docs/PISTAS-TURISMO.md,
// "Identidade"): passaporte, carimbo, cartão-postal — nunca "turnê" ou "world tour". Nome próprio de lugar não se
// traduz; o EN traduz a descrição ("Ponte Hercílio Luz" → "Hercílio Luz Bridge").
import { registerStrings } from '../../i18n';

/** Marcos do Brasil: [id, PT, EN]. */
const LANDMARKS: ReadonlyArray<readonly [string, string, string]> = [
  // Sudeste
  ['cristo_redentor', 'Cristo Redentor', 'Christ the Redeemer'],
  ['pao_de_acucar', 'Pão de Açúcar', 'Sugarloaf Mountain'],
  ['casario_paraty', 'Casario de Paraty', 'Paraty colonial houses'],
  ['escuna', 'Escunas da baía', 'Bay schooners'],
  ['dedo_de_deus', 'Dedo de Deus', 'Dedo de Deus peak'],
  ['masp', 'MASP', 'MASP art museum'],
  ['ponte_estaiada', 'Ponte Estaiada', 'Estaiada cable-stayed bridge'],
  ['farol_ilhabela', 'Farol de Ilhabela', 'Ilhabela lighthouse'],
  ['veleiro_canal', 'Veleiros do canal', 'Sailboats on the channel'],
  ['chale_enxaimel', 'Chalés enxaimel', 'Half-timbered chalets'],
  ['araucaria', 'Araucárias', 'Araucaria pines'],
  ['igreja_pampulha', 'Igreja da Pampulha', 'Pampulha church'],
  ['igreja_barroca', 'Igreja barroca', 'Baroque church'],
  ['casario_colonial', 'Casario colonial', 'Colonial houses'],
  ['casca_danta', 'Cachoeira Casca d\'Anta', 'Casca d\'Anta falls'],
  ['dunas_itaunas', 'Dunas de Itaúnas', 'Itaúnas dunes'],
  ['convento_penha', 'Convento da Penha', 'Penha convent'],
  ['terceira_ponte', 'Terceira Ponte', 'Terceira Ponte bridge'],
  ['pedra_azul', 'Pedra Azul', 'Pedra Azul rock'],
  // Sul
  ['cataratas_iguacu', 'Cataratas do Iguaçu', 'Iguaçu Falls'],
  ['ponte_amizade', 'Ponte da Amizade', 'Friendship Bridge'],
  ['trem_serra_verde', 'Trem da Serra Verde', 'Serra Verde train'],
  ['estufa_jardim_botanico', 'Estufa do Jardim Botânico', 'Botanical Garden greenhouse'],
  ['opera_de_arame', 'Ópera de Arame', 'Wire Opera House'],
  ['ponte_hercilio_luz', 'Ponte Hercílio Luz', 'Hercílio Luz Bridge'],
  ['igreja_acoriana', 'Igreja açoriana', 'Azorean church'],
  ['predios_camboriu', 'Prédios da orla', 'Beachfront towers'],
  ['roda_gigante', 'Roda-gigante', 'Ferris wheel'],
  ['mirante_rio_do_rastro', 'Mirante da Serra', 'Mountain lookout'],
  ['usina_gasometro', 'Usina do Gasômetro', 'Gasômetro power station'],
  ['catedral_de_pedra', 'Catedral de Pedra', 'Stone Cathedral'],
  ['cuia_chimarrao', 'Cuia de chimarrão', 'Chimarrão gourd'],
  ['canion_itaimbezinho', 'Cânion Itaimbezinho', 'Itaimbezinho Canyon'],
  // Centro-Oeste
  ['ponte_jk', 'Ponte JK', 'JK Bridge'],
  ['torre_tv_brasilia', 'Torre de TV', 'TV Tower'],
  ['congresso_nacional', 'Congresso Nacional', 'National Congress'],
  ['catedral_brasilia', 'Catedral de Brasília', 'Brasília Cathedral'],
  ['igreja_pirenopolis', 'Igreja Matriz', 'Mother church'],
  ['cavalhada', 'Cavalhadas', 'Cavalhadas festival'],
  ['parque_aquatico', 'Águas quentes', 'Hot springs park'],
  ['cachoeira_veadeiros', 'Cachoeiras da Chapada', 'Chapada waterfalls'],
  ['buriti', 'Buritis', 'Buriti palms'],
  ['gruta_lago_azul', 'Gruta do Lago Azul', 'Blue Lake Cave'],
  ['monumento_campo_grande', 'Monumento Maria Fumaça', 'Steam engine monument'],
  ['tuiuiu_ninho', 'Ninho de tuiuiú', 'Jabiru nest'],
  ['jacare', 'Jacarés', 'Caimans'],
  ['portal_transpantaneira', 'Portal da Transpantaneira', 'Transpantaneira gateway'],
  ['centro_geodesico', 'Centro Geodésico', 'Geodesic Center'],
  ['veu_de_noiva', 'Véu de Noiva', 'Bridal Veil falls'],
  // Nordeste
  ['igreja_quadrado', 'Igrejinha do Quadrado', 'Quadrado chapel'],
  ['coqueiral', 'Coqueiral', 'Coconut grove'],
  ['farol_da_barra', 'Farol da Barra', 'Barra lighthouse'],
  ['elevador_lacerda', 'Elevador Lacerda', 'Lacerda Elevator'],
  ['casario_pelourinho', 'Pelourinho', 'Pelourinho old town'],
  ['morro_pai_inacio', 'Morro do Pai Inácio', 'Pai Inácio hill'],
  ['arcos_atalaia', 'Arcos da Orla de Atalaia', 'Atalaia beachfront arches'],
  ['ponte_aracaju', 'Ponte Aracaju–Barra', 'Aracaju–Barra bridge'],
  ['praca_sao_francisco', 'Praça São Francisco', 'São Francisco Square'],
  ['canion_xingo', 'Cânion do Xingó', 'Xingó Canyon'],
  ['catamara', 'Catamarãs', 'Catamarans'],
  ['jangada', 'Jangadas', 'Jangada rafts'],
  ['farol_piacabucu', 'Farol do Pontal', 'Pontal lighthouse'],
  ['dunas_piacabucu', 'Dunas de Piaçabuçu', 'Piaçabuçu dunes'],
  ['marco_zero_recife', 'Marco Zero', 'Marco Zero square'],
  ['ponte_mauricio', 'Ponte Maurício de Nassau', 'Maurício de Nassau Bridge'],
  ['igrejas_olinda', 'Igrejas de Olinda', 'Olinda churches'],
  ['bonecos_olinda', 'Bonecos gigantes', 'Giant carnival puppets'],
  ['morro_do_pico', 'Morro do Pico', 'Morro do Pico peak'],
  ['dois_irmaos', 'Morro Dois Irmãos', 'Two Brothers hills'],
  ['farol_cabo_branco', 'Farol do Cabo Branco', 'Cabo Branco lighthouse'],
  ['estacao_cabo_branco', 'Estação Cabo Branco', 'Cabo Branco science station'],
  ['parque_do_povo', 'Parque do Povo', 'Parque do Povo festival grounds'],
  ['pedra_da_boca', 'Pedra da Boca', 'Pedra da Boca rock'],
  ['forte_reis_magos', 'Forte dos Reis Magos', 'Three Kings Fort'],
  ['ponte_newton_navarro', 'Ponte Newton Navarro', 'Newton Navarro Bridge'],
  ['morro_do_careca', 'Morro do Careca', 'Morro do Careca dune'],
  ['cajueiro_gigante', 'Maior Cajueiro do Mundo', 'World\'s Largest Cashew Tree'],
  ['pedra_furada_jeri', 'Pedra Furada', 'Pierced Rock'],
  ['duna_por_do_sol', 'Duna do Pôr do Sol', 'Sunset Dune'],
  ['ponte_dos_ingleses', 'Ponte dos Ingleses', 'English Pier'],
  ['falesias_canoa', 'Falésias', 'Sea cliffs'],
  ['manguezal_delta', 'Manguezal do Delta', 'Delta mangroves'],
  ['pedras_sete_cidades', 'Pedras de Sete Cidades', 'Sete Cidades rocks'],
  ['pedra_furada_capivara', 'Pedra Furada', 'Pierced Rock arch'],
  ['pinturas_rupestres', 'Pinturas rupestres', 'Rock paintings'],
  ['casario_azulejos', 'Casarões de azulejo', 'Tiled mansions'],
  ['morro_das_mesas', 'Morro das Mesas', 'Table mountains'],
  ['cachoeira_sao_romao', 'Cachoeira de São Romão', 'São Romão falls'],
  ['lagoas_lencois', 'Lagoas dos Lençóis', 'Lençóis lagoons'],
  ['farol_preguicas', 'Farol de Preguiças', 'Preguiças lighthouse'],
  // Norte
  ['praia_de_rio', 'Praia de rio', 'River beach'],
  ['barco_regional', 'Barcos regionais', 'River boats'],
  ['ver_o_peso', 'Ver-o-Peso', 'Ver-o-Peso market'],
  ['estacao_docas', 'Estação das Docas', 'Docks Station'],
  ['bufalo', 'Búfalos', 'Water buffalo'],
  ['palafita', 'Palafitas', 'Stilt houses'],
  ['teatro_amazonas', 'Teatro Amazonas', 'Amazon Theatre'],
  ['ponte_rio_negro', 'Ponte Rio Negro', 'Rio Negro Bridge'],
  ['bumbodromo', 'Bumbódromo', 'Bumbódromo arena'],
  ['marco_zero_equador', 'Marco Zero do Equador', 'Equator monument'],
  ['fortaleza_macapa', 'Fortaleza de São José', 'São José Fortress'],
  ['vila_serra_do_navio', 'Vila Serra do Navio', 'Serra do Navio village'],
  ['monumento_garimpeiro', 'Monumento ao Garimpeiro', 'Gold Miner monument'],
  ['tepui', 'Tepuis', 'Tepui table mountains'],
  ['maloca', 'Malocas', 'Indigenous longhouses'],
  ['locomotiva_mamore', 'Locomotiva da Madeira-Mamoré', 'Madeira-Mamoré locomotive'],
  ['caixas_dagua', 'Três Caixas d\'Água', 'Three Water Towers'],
  ['forte_principe_beira', 'Forte Príncipe da Beira', 'Príncipe da Beira Fort'],
  ['gameleira', 'Gameleira', 'Gameleira fig tree'],
  ['palacio_rio_branco', 'Palácio Rio Branco', 'Rio Branco Palace'],
  ['geoglifo', 'Geoglifos', 'Geoglyphs'],
  ['ponte_rio_acre', 'Ponte do Rio Acre', 'Acre River bridge'],
  ['castanheira', 'Castanheiras', 'Brazil nut trees'],
  ['serra_espirito_santo', 'Serra do Espírito Santo', 'Espírito Santo ridge'],
  ['dunas_jalapao', 'Dunas do Jalapão', 'Jalapão dunes'],
  ['palacio_araguaia', 'Palácio Araguaia', 'Araguaia Palace'],
  ['ponte_palmas', 'Ponte de Palmas', 'Palmas bridge'],
];

const pt: Record<string, string> = {
  'menu': 'Passaporte',
  'menu.hint': 'Os carimbos da Expedição Brasil e o cartão-postal de cada estado',
  'region': '{region} · {n}/{total}',
  'stamped': 'Carimbado',
  'notStamped': 'Sem carimbo',
  'postcard.from': 'Lembranças de',
  'postcard.tracks': 'Pistas',
  'postcard.landmarks': 'Marcos',
  'postcard.locked': 'Vença a {cup} para carimbar o passaporte e receber este cartão-postal.',
  'postcard.region': 'Região {region}',
  'hint': '←→↑↓ escolhe o estado · Esc ou B volta',
  'results.stamp': 'Carimbo',
  'results.regionDone': 'Região {region} completa!',
};
const en: Record<string, string> = {
  'menu': 'Passport',
  'menu.hint': 'Your Brazil Expedition stamps and a postcard from each state',
  'region': '{region} · {n}/{total}',
  'stamped': 'Stamped',
  'notStamped': 'Not stamped',
  'postcard.from': 'Greetings from',
  'postcard.tracks': 'Tracks',
  'postcard.landmarks': 'Landmarks',
  'postcard.locked': 'Win the {cup} to stamp your passport and get this postcard.',
  'postcard.region': '{region} region',
  'hint': '←→↑↓ pick a state · Esc or B goes back',
  'results.stamp': 'Stamp',
  'results.regionDone': '{region} region complete!',
};
for (const [id, p, e] of LANDMARKS) {
  pt[`landmark.${id}`] = p;
  en[`landmark.${id}`] = e;
}

registerStrings('passport', { pt, en });
